### ISSUE TITLE
Cannot find CPU backend on Ubuntu

### ISSUE THREAD

**Issue by AtheMathmo** [arrayfire/arrayfire-rust#100]
Hey!

I'm sure this is something stupid on my part but I can't seem to get the CPU backend working. I'm running my own crate on Ubuntu 14.04 with the arrayfire crate linked in my Cargo.toml. I followed the steps in the README and have checked that `ld` is finding the libraries correctly - but still when I try to run a test I get segfaults and cannot find any backends.

The code I'm trying to run is essentially pulled from the README:

```rust
let a = libaf::randu::<f32>(libaf::Dim4::new(&[2,2,1,1]));
```

Some outputs:

```
> sudo ldconfig -v | grep libaf
...
libafcuda.so.3 -> libafcuda.so.3.4.2
libafcpu.so.3 -> libafcpu.so.3.4.2
libaf.so.3 -> libaf.so.3.4.2
libafopencl.so.3 -> libafopencl.so.3.4.2
...
```

```
> cargo test
...
error: process didn't exit successfully: `/home/USER/.../target/debug/deps/lib-95ece5897579a04c` (signal: 11, SIGSEGV: invalid memory reference)
```

And `get_available_backends()` returns an empty `Vec`.

I've also double checked that `LD_LIBRARY_PATH` (and `DYLD_LIBRARY_PATH` from #86) both include my installation directory (with `/lib` appended).

Tomorrow I'll be trying this on my desktop with a CUDA backend, hopefully I can confirm it isn't an issue with the project then.

**Comment by pavanky** [comment]
@AtheMathmo can you try some C++ examples and see if they run fine?

**Comment by AtheMathmo** [comment]
I had to install glfw3 to compile the C++ example but sadly this hasn't resolved my rust issues. Also worth noting is that I had to specify the `ArrayFire_DIR` when using cmake (`cmake -DArrayFire_DIR=/usr/local/arrayfire-3/ArrayFire/share/ArrayFire/cmake ..`).

And here is the output when I ran the executables from the unified examples.

```
$ ./basic_unified 
Trying CPU Backend
Caught exception when trying CPU backend
ArrayFire Exception (Failed to load dynamic library. :501):
Error in af_err unified::AFSymbolManager::setBackend(af::Backend)
In file src/api/unified/symbol_manager.cpp:220
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

In function void af::setBackend(af::Backend)
In file src/api/cpp/device.cpp:22
Trying CUDA Backend
Caught exception when trying CUDA backend
ArrayFire Exception (Failed to load dynamic library. :501):
Error in af_err unified::AFSymbolManager::setBackend(af::Backend)
In file src/api/unified/symbol_manager.cpp:220
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

In function void af::setBackend(af::Backend)
In file src/api/cpp/device.cpp:22
Trying OpenCL Backend
Caught exception when trying OpenCL backend
ArrayFire Exception (Failed to load dynamic library. :501):
Error in af_err unified::AFSymbolManager::setBackend(af::Backend)
In file src/api/unified/symbol_manager.cpp:220
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

In function void af::setBackend(af::Backend)
In file src/api/cpp/device.cpp:22
```

And the `basic_cpu` is more mysterious

```
$ ./basic_cpu
./basic_cpu: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory
```

Just to confirm that the linker can find this library:

```
$ sudo ldconfig -v | grep glfw
...
libglfw.so.3 -> libglfw.so.3.1
...
```

**Comment by AtheMathmo** [comment]
It looks like the error on both the Rust and C++ side was glfw. Once I ran `ldconfig` it could successfully pick up glfw library and the CPU backend works.

I have another less severe issue which is that it recognizes an OpenCL backend but gets an `Unknown OpenCL Error` when trying to use it. I imagine this is an issue with my environment though.

I'll close this issue now.

**Comment by KrishnaPG** [comment]
Thanks @AtheMathmo for sharing the `ldconfig` tip. I was facing the same problem and after trying many things, finally running `ldconfig` solved the problem in a second. Thanks.
