### ISSUE TITLE
Implement arithmetic ops for &Array vs &Array

### ISSUE THREAD

**Issue by AtheMathmo** [arrayfire/arrayfire-rust#103]
Is there any reason why arithmetic overloading only exists for `Array`-`Array`? Given that the `arrayfire::add/sub/mul` functions all take `&Array` arguments it seems like it is worth having the extra syntactic sugar.

Just to be clear, I mean implementations like this:

```rust
impl<'a> Add<&'a Array> for Array { }
impl<'a> Add<Array> for &'a Array { }
impl<'a, 'b> Add<&'a Array> for &'b Array { }
```

Internally these would just call `arrayfire::add`.

**Comment by 9prady9** [comment]
@AtheMathmo I have addressed these changes in https://github.com/arrayfire/arrayfire-rust/pull/104. The new features will be available in next release.

**Comment by AtheMathmo** [comment]
Awesome, thank you!
