### ISSUE TITLE
Dimension mismatch with tile

### ISSUE THREAD

**Issue by AtheMathmo** [arrayfire/arrayfire-rust#108]
I'm not sure if this is a bug, but I'd argue that if not the docs should be improved. I have the following code example:

```rust
#[macro_use]
extern crate arrayfire as af;

use af::{Array, Dim4, tile};
use af::print_gen;

fn main() {
    // Set the backend
    af::set_backend(af::Backend::CPU);

    let vec_dims = Dim4::new(&[4,1,1,1]);
    let two_d_dims = Dim4::new(&[4,3,1,1]);

    let vec_arr = Array::new(&[0.5; 4], vec_dims);
    let two_d_arr = Array::new(&[1.5; 12], two_d_dims);

    let tiled = af::tile(&vec_arr, two_d_dims);

    af_print!("The Vector", vec_arr);
    af_print!("The 2d Array", two_d_arr);
    af_print!("Tiled array", tiled);
}
```

I get the following output:

```
The Vector
[4 1 1 1]
    0.5000 
    0.5000 
    0.5000 
    0.5000 

The 2d Array
[4 3 1 1]
    1.5000     1.5000     1.5000 
    1.5000     1.5000     1.5000 
    1.5000     1.5000     1.5000 
    1.5000     1.5000     1.5000 

Tiled array
[16 3 1 1]
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000
```

But the documentation states that: 

> Tile the input array along specified dimension
> 
> ## Parameters
> 
> - input is the input Array
> - dims is the target(output) dimensions

So I would expect the tiled array to have dimensions `[4, 3, 1, 1]`, and look like this:

```
Tiled array
[4 3 1 1]
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
    0.5000     0.5000     0.5000 
```

---

I'm running this on Ubuntu 14.04, with a CPU backend.

If this is expected behaviour - is there a way to achieve what I want?

**Comment by AtheMathmo** [comment]
I've researched a little more and I can see that the function is working as intended. I do think the docs should be updated to clarify what this function does.

I also cant find a rust binding for the arrayfire broadcast function in this library. Am I missing something there?

**Comment by pavanky** [comment]
@AtheMathmo you need to pass `[1, 3, 1, 1]` for what you want. The tile dims is the number of times you want to repeat along each dimension.

**Comment by AtheMathmo** [comment]
Is there a way to get the broadcasting functionality I want?

**Comment by pavanky** [comment]
@AtheMathmo tile and broadcast are identical internally. Can you tell me specifically how you want to use broadcast ?

**Comment by AtheMathmo** [comment]
I have two arrays `a` and `b` which I want to multiply (`arrayfire::mul`). I know that `a` is smaller than `b` and that it can be broadcast to it's shape. So I want to do something like:

```rust
// Where a and b are `Array`s
let b_dims = b.dims();
let a_full = arrayfire::broadcast(&a, b_dims);

arrayfire::mul(a_full, b, false)
```

To do this with the current tiling I have to do something like:

```rust
// Get b's dims (Being able to `Index` Dim4 would be helpful here)
let b_1_dim = b.dims().get()[0];
let b_2_dim = b.dims().get()[1];

// Get a's dims
let a_1_dim = a.dims().get()[0];
let a_2_dim = a.dims().get()[1];

let a_dim_1_tile_count = b_1_dim / a_1_dim;
let a_dim_2_tile_count = b_2_dim / a_2_dim;

// Tile it to fit the first two dimensions
let a_full = arrayfire::tile(&a, Dim4::new(&[a_dim_1_tile_count, a_dim_2_tile_count, 1, 1]));

arrayfire::mul(a_full, b, false)
```

This approach is verbose and only works for 2d arrays. Is there a more natural way to do this?

**Comment by pavanky** [comment]
@AtheMathmo Whatever you are doing is more or less what is happening internally inside the broadcast function :) I'd say create a function called `tile_as` or `broadcast` that replicates this behavior. 

In fact, if you can generalize it for 4 dimensions and send it in as a PR, that'd be great!

**Comment by pavanky** [comment]
@AtheMathmo Actually none of this is required! I did not realize `mul` has the batch / broadcast parameter! 

You can simply do `arrayfire:mull(a, b, true)`

**Comment by pavanky** [comment]
@9prady9 May be add some examples to the documentation to show how the difference between the true and false cases for the third parameter?

**Comment by AtheMathmo** [comment]
Ah! I did not realise that this is what that parameter does! I assumed it was for some GPU optimisation or something. Thanks for pointing this out to me!

**Comment by AtheMathmo** [comment]
@pavanky - I do actually have a situation where I need to broadcast without an operation. Would you still welcome a PR adding this functionality?

**Comment by pavanky** [comment]
@AtheMathmo Sure!
