### ISSUE TITLE
Matlab equivalent examples

### ISSUE THREAD

**Issue by Timmmm** [arrayfire/arrayfire-rust#114]
Closely related to #52 but it might be nice if there was a sort of translation table for people coming from Matlab:

| Matlab | arrayfire-rust |
|---------|----------------|
| `a = zeros(3, 4)` | `let mut a = constant::<f32>(0.0, Dim4::new(&[3, 4, 1, 1]));` |
| `b = a * 2` | `let mut b = a * 2.0f32;` |
| `c = 0:10` | `let mut c = range::<f32>(Dim4::new(&[10, 1, 1, 1]), 0);` |
| `d = (0:10)'` | `let mut d = range::<f32>(Dim4::new(&[1, 10, 1, 1]), 1);` |
| `e = d * c` | `let mut e = d * c` |
| `f = 1 - e` | ??? |
| `g = max(c, 5)` | ??? |
| `g(2:4) = 4` | ??? |

[Here is an example of this for NumPy](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#general-purpose-equivalents).

**Comment by 9prady9** [comment]
@Timmmm please feel free to contribute.

**Comment by 9prady9** [comment]
I have created a repository for such information for comparison across wrappers and frameworks.
https://github.com/arrayfire/arrayfire-api-cheat-sheet

Any further information related this will be handled in that repository.
