### ISSUE TITLE
svd_inplace: 'Error message: Size is incorrect'

### ISSUE THREAD

**Issue by rennis250** [arrayfire/arrayfire-rust#120]
Hey there,

I am trying to use the arrayfire-rust interface to accelerate some image processing here at the lab. I want to do PCA by using SVD directly, but it appears to fail for certain sizes that Matlab can do without trouble. I think I found a pattern for which size matrices it accepts and for which it fails, but I am not sure. Also, is there a way to do a thin SVD? That would be preferred for our cases, since our data will be rather large and it seems the current SVD implementation takes up gigabytes of memory for cases that should be rather simple for it... I don't know much about that stuff, though... Anyway, here is example code that fails:

```rust
extern crate arrayfire as af;

use af::*;

fn main() {
    set_backend(Backend::CUDA); // it is not related to backend

    let w = 4000u64;
    let h = 400u64;
    let mut d = Array::new(&vec![20f64; w as usize * h as usize],
                           Dim4::new(&[w, h, 1, 1]));

    let (u, s, vt) = svd_inplace(&mut d);
}
```

Curiously enough, if I use ```svd()``` instead of ```svd_inplace()```, then it works, but naturally runs much slower than preferred.

~~Also, strangely, if I pass it a matrix with ```Dims = &[800, 53, 400, 1]```, then it also works, which shouldn't be the case for SVD, as far as I understand. What Arrayfire seems to do is ignore the second dimension and perform on SVD on a matrix of 800x400 elements, considering the sizes of U, S, and Vt after it completes... Matlab gives an error if I try to do this.~~

_**^^- See replies below! I was mistaken here!**_

Here are some example sizes where ```svd_inplace()``` succeeds:

- w = 400, h =400
- w = 4000, h = 4001
- w = 6000, h = 10

```svd()``` works for these and their transposes.

```svd_inplace()``` seems to always work when ```w < h```? I don't find anything in the documentation, on github issues/pull requests, or in the source code of Arrayfire itself that warns about any of this.

The system is Ubuntu 14.04. Here is the Arrayfire ```info()``` output:

```
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build 512bf69)
Platform: CUDA Toolkit 8, Driver: 375.39
[0] Quadro K5000, 4034 MB, CUDA Compute 3.0
```

Operating system and Arrayfire versions seem to be irrelevant, though. I get the same results on Mac with the CPU and OpenCL backends and with Arrayfire v3.4.2.

I tried a few of the C++ examples and they work and all of the Rust examples work. I cannot tell if this is due to Arrayfire or Rust.

Best,
Rob

**Comment by pavanky** [comment]
The limitation comes from the C++ library using  cuSolver (for CUDA) and clMagma (for OpenCL) which d not support W > H. For regular SVD, a transpose is performed and u, v are changed accordingly. This should be better documented.

>  Also, strangely, if I pass it a matrix with Dims = &[800, 53, 400, 1], then it also works, which shouldn't be the case for SVD, as far as I understand. What Arrayfire seems to do is ignore the second dimension and perform on SVD on a matrix of 800x400 elements,

I looked at the source code, it should be performing SVD on 800 x 53. Can you double check if it is really performing on 800 x 400?. The error checking mechanism in the C++ library has `numdims <= 3` instead of `numdims < 3` which results in the check not happening properly for 3D inputs.

**Comment by rennis250** [comment]
Sorry, it's been a long few days recently. I was doing SVD on a matrix with shape = (800, 400, 53), so it was doing SVD on the 800x400 first elements.

So, I assume then that there is this limit on the matrix size? Sample data for us are typically of a size = (800*500 rows, 400 columns) on average, with some data files having twice as many rows. Currently, this won't fit in the memory of our GPU and only works on our computer that has 256GB of RAM. I assume that this limitation is coming from the CUDA and OpenCL libraries? Is there any other option for performing PCA by hand in Arrayfire?

**Comment by pavanky** [comment]
@rennis250 SVD on CPU backend should be using MKL if you are using the installer and should perform decently well. But it looks like you built it yourself. Can you run ldd on `libafcpu.so` to show what lapack you are using ?

**Comment by rennis250** [comment]
I used the installer on my Mac, which I can currently access. If I run the following code, it seems to finish in 0.7 seconds:

```rust
extern crate arrayfire as af;

use af::*;

fn main() {
    set_backend(Backend::CPU);
    info();

    let w = 400u64;
    let h = 800 * 53 as u64;
    let d = Array::new(&vec![20f32; w as usize * h as usize],
                       Dim4::new(&[w, h, 1, 1]));

    let (u, s, vt) = svd(&d);
}
```

If I use ```svd_inplace()``` instead, then it takes longer than 3 mins and I had to cancel it.

On the other hand, if I stick with ```svd()``` and add the following code to print the first eigenvector, then it also takes >3 mins and I had to cancel the process:

```rust
let seqs = &[Seq::new(0u32, 0, 1), Seq::default()];
let sub = index(&vt, seqs);
af_print!("d(seq(1,3,1), span)", sub);
```

I assume this is because of transferring data around? I don't understand why, though, since it is being done on the CPU backend and presumably the data should be easily accessible? The printing is what seems to have confused me though. I will continue with writing our code now and will report back if I experience any other slowdowns along the way.

Best,
Rob

**Comment by pavanky** [comment]
@9prady9 can you look into this and report the performance ?

**Comment by 9prady9** [comment]
@pavanky 

For the GPU(GT 650M, 2G) on my laptop, i see the following results.

400x800
```
svd inplace runtime Duration { secs: 0, nanos: 112065652 }
svd(out, in) runtime Duration { secs: 0, nanos: 524054109 }
```

400x800*2
```
svd inplace runtime Duration { secs: 0, nanos: 112468680 }
svd(out, in) runtime Duration { secs: 1, nanos: 317314138 }
```

400x800*4
```
svd inplace runtime Duration { secs: 0, nanos: 90621751 }
svd(out, in) runtime Duration { secs: 4, nanos: 322869378 }
```

400x800*8
```
svd inplace runtime Duration { secs: 0, nanos: 88657693 }
svd(out, in) runtime Duration { secs: 16, nanos: 441185735 }
```

400x800*16
```
svd inplace runtime Duration { secs: 0, nanos: 94144830 }
svd(out, in) runtime Duration { secs: 65, nanos: 388398774 }
```

400x800*32
```
In this case, i got out of memory error.
```
Runtime of Ouput version of svd function keeps increasing significantly with the size compared to the inplace version.

**Comment by pavanky** [comment]
@9prady9 are you running a sync ? Can you run this on the CPU as well ?

**Comment by 9prady9** [comment]
Yes, i did sync before printing out the elapsed time.

**Comment by 9prady9** [comment]
```
ArrayFire v3.4.2 (CPU, 64-bit Linux, build 2da9967)
[0] Intel: Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz, 7869 MB, Max threads(8) 
```

400x800*1
```
svd(out, in) runtime Duration { secs: 0, nanos: 835028218 }
svd(out, in) runtime Duration { secs: 0, nanos: 822413671 }
```

400x800*2
```
svd(out, in) runtime Duration { secs: 1, nanos: 225447242 }
svd(out, in) runtime Duration { secs: 1, nanos: 233202431 }
```

400x800*4
```
svd(out, in) runtime Duration { secs: 2, nanos: 777632499 }
svd(out, in) runtime Duration { secs: 2, nanos: 691638789 }
```

400x800*8
```
svd(out, in) runtime Duration { secs: 7, nanos: 712560857 }
svd(out, in) runtime Duration { secs: 7, nanos: 570376825 }
```

400x800*16
```
svd(out, in) runtime Duration { secs: 21, nanos: 590935005 }
svd(out, in) runtime Duration { secs: 21, nanos: 658253983 }
```

400x800*32
```
svd(out, in) runtime Duration { secs: 76, nanos: 736588629 }
svd(out, in) runtime Duration { secs: 85, nanos: 236914641 }
```

As you can see, for smaller sizes the runtime difference is not much. However, it increases as the size increases.

**Comment by rennis250** [comment]
I've been doing more testing and I think my issue is coming from problems with printing certain matrices. I'm closing this in favor of a more specific issue.
