### ISSUE TITLE
Multiple uses of svd or svd_inplace in the same program cause it to stall

### ISSUE THREAD

**Issue by rennis250** [arrayfire/arrayfire-rust#123]
I've found that calling SVD functions more than once in the same program cause it to stall and start eating up lots of memory. It seems to be independent of whether you use ```svd``` or ```svd_inplace```. It is also independent of whether you use the same array repeatedly or not. An example program:

```rust
extern crate arrayfire as af;

use af::*;

fn main() {
    set_backend(Backend::CPU);

    for x in 40000..50000 {
        let w = 400u64;
        let h = x as u64;

        let dims = Dim4::new(&[w, h, 1, 1]);
        let mut d: Array = randu::<f32>(dims);
        let mut e: Array = randu::<f32>(dims);
        if x == 40000 {
            println!("{}", d.dims());
        } else {
            println!("{}", e.dims());
        }

        println!("before svd");
        if x == 40000 {
            let (u, s, vt) = svd(&mut d);
        } else {
            let (u, s, vt) = svd(&mut e);
        }
        println!("after svd");
    }
}
```

On my Mac with 8GB of RAM, the second iteration of the loop hangs and starts eating up RAM. I'm using ArrayFire from the installer, Rust 1.16.0, and the latest version of this crate from crates.io. I will be able to test on a Linux machine later.

**Comment by rennis250** [comment]
On the Linux machine, which has 256GB of RAM, the loop hangs after 5 iterations. I'm also finding that SVD on the Linux machine cannot handle matrices of about 800x200x400 elements. It runs out of RAM, but that would be considered a small data file for us.

**Comment by rennis250** [comment]
It seems the size limitation is coming from Rust(??), not from the underlying libraries. If I translate a similar version of this to C++, then I can make the matrices much larger and SVD works fast and correctly.

**Comment by rennis250** [comment]
And the problem of multiple SVDs in one block of code is coming from the underlying ArrayFire libraries: arrayfire/arrayfire#1746

**Comment by 9prady9** [comment]
@rennis250 I did run the code you shared on both CPU and CUDA backend. CPU backend is eating up almost all of the RAM although it runs. However, CUDA is running out of memory.

`Note: I have 8GB RAM machine with GT650M card with 2GM GPU memory.`

I think the core issue stems from either upstream ArrayFire or the libraries ArrayFire uses for SVD implementation. I am fairly confident that is the case because svd implementation in rust wrapper looks like below - it is pure call delegation to ArrayFire's C API, nothing else.

```rust
pub fn svd(input: &Array) -> (Array, Array, Array) {
    unsafe {
        let mut u: i64 = 0;
        let mut s: i64 = 0;
        let mut vt: i64 = 0;
        let err_val = af_svd(&mut u as MutAfArray, &mut s as MutAfArray, &mut vt as MutAfArray,
                             input.get() as AfArray);
        HANDLE_ERROR(AfError::from(err_val));
        (Array::from(u), Array::from(s), Array::from(vt))
    }
}
```

**Comment by 9prady9** [comment]
Closing this issue as this very likely upstream or upstream's dependency related. Upstream already has an active issue whose progress can be tracked here https://github.com/arrayfire/arrayfire/issues/1746
