### ISSUE TITLE
dot throws 'Type is not suppported by this function' error

### ISSUE THREAD

**Issue by lobachevzky** [arrayfire/arrayfire-rust#125]
Sorry to bombard you guys. This code:
```rust
    let vec1 = af::constant(1, Dim4::new(&[1, 1, 1, 1]));
    let vec2 = af::constant(1, Dim4::new(&[1, 1, 1, 1]));
    let prod = af::dot(&vec1, &vec2, af::MatProp::NONE, af::MatProp::NONE);
```
throws the following error:
```
thread 'main' panicked at 'Error message: Type is not suppported by this function', /Users/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.2/src/error.rs:66
stack backtrace:
   1:        0x10e37e6ca - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
   2:        0x10e37f91f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
   3:        0x10e37f5c7 - std::panicking::default_hook::h88ffbc5922643264
   4:        0x10e37fd86 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
   5:        0x10e37fc24 - std::panicking::begin_panic::hc066339e2fdc17d1
   6:        0x10e37fb42 - std::panicking::begin_panic_fmt::h5912b2d2df332044
   7:        0x10e3791e5 - arrayfire::error::handle_error_general::hf359710f41e1117d
   8:        0x10e379712 - core::ops::Fn::call::h14f527962095825a
   9:        0x10e37933c - arrayfire::error::HANDLE_ERROR::he9ee51b98f993f43
  10:        0x10e378b33 - arrayfire::blas::dot::hcba6182d2c9a7641
  11:        0x10e376940 - raytracer::main::h5b720a32616b76ca
  12:        0x10e38071a - __rust_maybe_catch_panic
  13:        0x10e37fff6 - std::rt::lang_start::h5d71a3afaaa4b2ff
  14:        0x10e376ac9 - main
ArrayFire v3.3.2 (OpenCL, 64-bit Mac OSX, build f65dd97)
[0] APPLE   : Iris Pro, 1536 MB
```
What am I missing?

**Comment by 9prady9** [comment]
@lobachevzky Rust's `af::constant` is a generic function. I believe the problem here is that the first parameter passed to this function is used for type inference of the constant af::Array to be created. In Rust, i believe 1 defaults to integer type. Though were able to create such Array's dot doesn't have support for integral types. It only works on float, double, complex-float, complex-double types.

**Comment by 9prady9** [comment]
To add to my above comment. You can still do dot using the following work around.

```rust
let prod = af::dot(&vec1.cast::<f32>(), &vec2.cast::<f32>(), 
                   af::MatProp::NONE, af::MatProp::NONE);
```

if you don't want to change the type of the original Array.

**Comment by lobachevzky** [comment]
Ah thank you. So I was able to get that example to work but now this example:
```rust
    let vec1 = af::constant(1_f32, Dim4::new(&[2, 2, 1, 1]));
    let vec2 = af::constant(1_f32, Dim4::new(&[2, 1, 1, 1]));
    let prod = af::dot(&vec1, &vec2, af::MatProp::NONE, af::MatProp::NONE);
```

Throws 
```
thread 'main' panicked at 'Error message: Function does not support GFOR / batch mode', /Users/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.2/src/error.rs:66
```
The documentation seemed to indicate that `dot` could handle matrix vector operations.

**Comment by 9prady9** [comment]
Unfortunately, dot currently cannot be used in batch mode or inside GFOR. The support for batched dot is not baked in yet. 

A straightforward work around would be to use a standard for-loop to run dot on each column (use indexing to get each column) against the Array with single column. As the arrayfire function calls are asynchronous, each iteration doesn't block the processing of it's subsequent iteration. May be there is a better alternative than this, but i need to think about it.

**Comment by lobachevzky** [comment]
Perfect. Matmul works. thanks.
