### ISSUE TITLE
broadcasting and scalar / array ops

### ISSUE THREAD

**Issue by lobachevzky** [arrayfire/arrayfire-rust#126]
Thank you so much for all your help so far! I'm really enjoying using the library and I think my project is really shaping up as a result.

I was wondering what the most performant way would be to perform broadcast operations: eg. multiply an array with dimension `[n 1 1 1]` by an array with dimension `[n m 1 1 ]` (currently I am using `join_many').

On a slightly unrelated note, if an array contains a single f32 element, is there a way to extract it (cast it to f32)?

Thanks again!

**Comment by 9prady9** [comment]
The only way to extract data from GPU to CPU is to use [Array::host](http://arrayfire.org/arrayfire-rust/arrayfire/struct.Array.html#method.host) member function.

Do you mean element-wise multiplication of n elements for m different data sets ? where one input is [n 1 1 1] and the other is [n m 1 1] ? If that is what you are asking, I believe [mul](http://arrayfire.org/arrayfire-rust/arrayfire/fn.mul.html) should be able to do that.

```rust
    let num_rows: u64 = 5;
    let num_cols: u64 = 3;
    let values: [f32; 3] = [1.0, 2.0, 3.0];
    let indices = Array::new(&values, Dim4::new(&[3, 1, 1, 1]));

    let dims1 = Dim4::new(&[num_rows, 1, 1, 1]);
    let dims2 = Dim4::new(&[num_rows, num_cols, 1, 1]);
    let dims_tile = Dim4::new(&[1, num_cols, 1, 1]);

    let a = constant(1_f32, dims1);
    let b = constant(2_f32, dims2);
    af_print!("Column Vector", a);
    af_print!("Matrix", b);
    let c = tile(&a, dims_tile);
    let d = mul(&c, &b, false);
    let e = mul(&a, &b, true);
    af_print!("Tile based mul: ", d);
    af_print!("Batch mul", e);
```

**Comment by lobachevzky** [comment]
Thanks so much. Tile was the function that I needed.
