### ISSUE TITLE
Shift to serde from rustc-serialize: rustc-serialize deprecated

### ISSUE THREAD

**Issue by dtolnay** [arrayfire/arrayfire-rust#129]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by pavanky** [comment]
@dtolnay care to send in a PR ?

**Comment by dtolnay** [comment]
Nope, just canvassing to make sure you've planned for it in case it affects your API. :slightly_smiling_face:

**Comment by pavanky** [comment]
@dtolnay Thanks for the heads up.

**Comment by 9prady9** [comment]
Thanks @dtolnay . The replacement crate is [serde](https://crates.io/crates/serde). Renaming the issue to reflect the shift to serde.

**Comment by pavanky** [comment]
@9prady9 what is this used for ? Do we really need it?

**Comment by 9prady9** [comment]
It is build dependency, not used by crates that are used by users. It is only needed by someone who is developing arrayfire-rust.

**Comment by 9prady9** [comment]
It is used to parse the json config file.

**Comment by 9prady9** [comment]
I have been thinking about it for a while now - we can remove this dependency if the rust wrapper doesn't try to build arrayfire locally - separate from installed binaries.

**Comment by 9prady9** [comment]
@pavanky and @jramapuram What do you guys think about my last comment of removing option to build ArrayFire locally ?

**Comment by jramapuram** [comment]
Should be fair enough that AF is expected to be installed. I liked having the af as a submodule because it keeps the tight coupling as well. If we can be a little more explicit about this that would be good.

**Comment by 9prady9** [comment]
I have no objections to either way of doing it. We just have to update the current config and build file to reflect latest changes in build procedure.
