### ISSUE TITLE
Port all functions from ArrayFire 3.0

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-rust#13]
Import from each header file into unique source files.

- [x] algorithm
- [x] arith
- [x] array
- [x] blas
- [x] data
- [x] defines
- [x] device
- [x] features
- [x] graphics
- [x] image
- [x] index
- [x] lapack
- [x] signal
- [x] statistics
- [x] util
- [x] version
- [x] vision

---
C++ only headers that need not be ported

- exception.h (ported the necessary C function to util.py)
- complex.h
- dim4.hpp
- gfor (are there any necessary bits??)
- constants

**Comment by jramapuram** [comment]
Not sure we have `gfor` yet though. I don't see a `C` API for it though

**Comment by pavanky** [comment]
GFOR is just a macro with a global flag that is toggled. Depending on the state of the flag, the indexing / assignment operations are "reorder"ed and the "batch" flag for binary operations is set to true.

C API is not / should not be aware of this.

**Comment by 9prady9** [comment]
All the functions from 3.0 are in arrayfire-rust now.

**Comment by polarathene** [comment]
Could you clarify about GFOR? Does Rust already handle the optimization by default or does it miss out on this performance gain? If latter can a Rust macro be added?

**Comment by 9prady9** [comment]
@polarathene GFOR is just syntactic sugar for batch operations in ArrayFire. All batch operations that can be done at C++ level using GFOR can be done in our C-API, which is what the rust wrapper wraps up without excluding any applicable capabilities. So, the answer to you question - no you are not missing out on any performance using rust wrapper. You can still do all the batch operations over here, just the GFOR construct is not made available.

Sure, may be a macro can be added but i believe a compiler plugin to handle gfor style code is more appropriate and scalable solution.

**Comment by polarathene** [comment]
@9prady9 In [this C++ example](http://arrayfire.org/docs/getting_started_2vectorize_8cpp-example.htm), GFOR is shown as an improvement. [This 2013 blog article](http://blog.accelereyes.com/blog/2013/03/04/arrayfire-examples-part-1-of-8-getting-started/) also mentions it giving a 3.1x perf improvement.

What happens on the Rust end instead if I were to write a similar loop? Do I instead call methods and set the [bool flag for batch](http://arrayfire.org/arrayfire-rust/arrayfire/fn.add.html) as true? 

I'm not quite sure how to interpret what you're saying about GFOR, it's handled at the C++ level which the C-API/rust-wrapper does not cover, but we're not missing out. Perhaps I've misunderstood and that there is more control when working with ArrayFire with C++ directly where you'd use GFOR, but with the C-API Rust is calling methods that are already optimized with GFOR where appropriate?

**Comment by 9prady9** [comment]
The post you are referring to is written earlier to open sourcing ArrayFire library. A lot of changes has happened internally and it wouldn't be apt to compare the results posted on that post with current code base.

Many functions handle batch operations automatically when it is applicable. Example of such functions are convolve and other image processing functions. In certain cases, the user has to inform the algorithm of it's batch nature explicitly. In such cases, the bool flag you have pointed out helps.

I am sorry if i have confused you. As i have said earlier, GFOR is just a macro and what can be done using it can also be done without using it. You can take a look at the below files to get an idea of what the gfor macro does.
- [gfor.h](https://github.com/arrayfire/arrayfire/blob/devel/include/af/gfor.h)
- [gfor.cpp](https://github.com/arrayfire/arrayfire/blob/devel/src/api/cpp/gfor.cpp)

GFOR essentially reorders the array data (move data along the batch dimension to be fourth dimension - largest dimension possible right now for ArrayFire array) and then calls the function with the batch flag set to true. This data reorder can be done by user as well, it is not something fancy or complicated. Please keep in mind that the data reordering happens at C API level, so our C++ API is also just a wrapper on top of C-API.

**Comment by jramapuram** [comment]
Just to clarify also: most of the methods accept a "batch" flag. eg:

```rust
af::add(&Array0, &Array1, <batch_flag = true if batch op is reqd>);
```
