### ISSUE TITLE
"arrayfire::replace_scalar" Has Opposite Replacement which Replaces when True, Not False

### ISSUE THREAD

**Issue by heartsh** [arrayfire/arrayfire-rust#133]
Hi, I'm a user of ArrayFire in Rust.

The function seems to have the above wrong replacement.
In the document, it should replace when false, not true.
To be consistent with the document and "arrayfire::replace", it should be fixed.

**Comment by 9prady9** [comment]
@heartsh I am confused, can you please explain if the mistake in the documentation or code is producing wrong results ? If it is code, can you please show us the code you have tried.

**Comment by heartsh** [comment]
My code is complicated, so I show an example about it below:
```rust
extern crate arrayfire as arfr;

use arfr::*;

fn main() {
  let mut ons = constant(1. as f32, Dim4::new(&[1_000, 1_000, 1, 1]));
  let trs = constant(true, ons.dims());
  replace_scalar(&mut ons, &trs, 0.);
  print(&ons); // "ons", array of 1's should be not changed, however, it would become array of 0's
}
```
The version of ArrayFire in Rust is 3.4.3 and everything else has no problem.

**Comment by 9prady9** [comment]
I am looking into it.

**Comment by 9prady9** [comment]
@heartsh This seems to be bug in upstream. I have raised an [issue in ArrayFire repository](https://github.com/arrayfire/arrayfire/issues/1772). Thank you for reporting it. This should be get fixed with next ArrayFire release. Will leave this issue open as placeholder.

**Comment by heartsh** [comment]
@9prady9 
I see.
Thank you for your corresponding.
