### ISSUE TITLE
Array::host, a safe method, can easily cause memory unsafety

### ISSUE THREAD

**Issue by daboross** [arrayfire/arrayfire-rust#135]
Correct me if I'm wrong, but it seems that https://github.com/arrayfire/arrayfire-rust/blob/ce74da05f095a30bd3a58a6b4f726824bee40389/src/array.rs#L311 checks neither T nor the length of the array to see if they are correct.

In Rust this should either be an unsafe method, or it should have runtime checks on the slice's length and type.

Using `host::<String>()` for example will give you a bunch of invalid strings - without using `unsafe`. Using said strings would violate memory safety, and likely cause programs to crash when the strings are deallocated.

I'm really interested in `arrayfire` in Rust, but it'd be even better if it adhered to Rust library principles. Methods which can violate safety with safe user input should be marked as `unsafe` to indicate this.

**Comment by daboross** [comment]
I believe part of this could be solved by requiring `T: HasAfEnum` on the type, and then making `HasAfEnum` an `unsafe trait`.

`unsafe trait`s must be explicitly implemented using `unsafe` in user code, so the user knows they are doing something unsupported when implementing it.

At least with that, this would no longer be a safety violation (where any T even Box or String can be passed in).

**Comment by 9prady9** [comment]
@daboross Sure, that is a bug - the generic's trait bound is missing for `Array::host` method. 

I believe adding the HasAfEnum trait bound and a check for slice's length against the output of `Array::elements()` should take care of the memory safety concerns you have expressed. After these changes, do you still think HasAfEnum should be marked unsafe ?

**Comment by daboross** [comment]
@9prady9 that would be great! I don't think it would need `unsafe` if it requires HasAfEnum, as it could not cause data unsafety.
