### ISSUE TITLE
need a example on indexing 

### ISSUE THREAD

**Issue by ultimaRatio** [arrayfire/arrayfire-rust#137]
Hi,

i'm trying to extract channels from an image, like in the following example : http://blog.accelereyes.com/blog/2013/04/16/arrayfire-examples-part-4-of-8-image-processing/
```
static void channel_split(array& rgb, array& outr, array& outg, array& outb) {
    outr = rgb(span, span, 0);
    outg = rgb(span, span, 1);
    outb = rgb(span, span, 2);
}
```
It doesn't seem to be possible, at least not that easily.

I haven't found span but it can be replaced with a seq, but i've been unable translate this example in Rust.

if someone could give me a hint :-)

**Comment by polarathene** [comment]
There are some vague docs here: https://github.com/arrayfire/arrayfire-rust/blob/devel/doc/getting_started.md#indexing

And a few examples of it in the repo examples folder. Here is one from there:
```Rust
// Index array using sequences
let seqs = &[Seq::new(1u32, 3, 1), Seq::default()];
let sub = index(&a, seqs);
af_print!("a(seq(1,3,1), span)", sub);
```
So a span equivalent is `Seq::default()`, the `index()` method takes an array and a sequence. I'm not sure but I guess for a single value like in that example it would still need to use `Seq::new()`?

The following is what works for me if you rather use an array of indices:
```
// Create a new array with an array of indices applied to your input array
fn filter(array: &af::Array, indices: &af::Array) -> af::Array {
    let mut idxr = af::Indexer::new();
    idxr.set_index(indices, 0, None);
    af::index_gen(array, idxr)
}

// [2,5,6] with [1,0,1] produces [5,2,5]
filter(&array,  &indices);

// Or use a boolean array with locate to convert to filtered indices, eg [2,5,6] with [1,0,1] produces [2,6]
filter(&array,  &af::locate(&bools));
```

**Comment by ultimaRatio** [comment]
thanks for your help, but I've stop fighting with indexing (one could say i've lost :-) )

I think I've just made a bad analysis on the problem.
This example is fine when it's easy to extract the 3 channels from a [height,width,4,1] array.

But when if it's not that easy, it's easier to simply shape (Array::new) or reshape (with moddims) the array to something like [4, height*width, 1, 1] and simply extract row 0, row 1 and row 2.
I just need to be sure that moddins is not way slower than indexing.

sorry for the noise, and thanks again for you help :-)

**Comment by polarathene** [comment]
```
static void channel_split(array& rgb, array& outr, array& outg, array& outb) {
    outr = rgb(span, span, 0);
    outg = rgb(span, span, 1);
    outb = rgb(span, span, 2);
}
```

would convert to

```
// Takes an array with dims [width, height, rgb, 1]
// Returns tuple of individual channels
fn channel_split(rgb: &af::Array) -> (af::Array, af::Array, af::Array) {
    // Use all width and height pixels
    let span = Seq::default();

    // Only take a single element from the third dim for each channel
    let r = index(rgb, &[span, span, Seq::new(0, 0, 1)] );
    let g = index(rgb, &[span, span, Seq::new(1, 1, 1)] );
    let b = index(rgb, &[span, span, Seq::new(2, 2, 1)] );

    (r, g, b)
}

// Usage
let (r,g,b) = channel_split(&rgb);
```

I don't know if the third dim has to be selected like that for individual indices, might be a better way. For more complex indexing I can try help if  you have example.

**Comment by ultimaRatio** [comment]
thanks, it's clearer now ... but it doesn't work (or i've missed something)

let's take a small example.
if you do this :    
 ```
let tmp = load_image("file.jpg".to_string(), true);
println!("{:?}",tmp.dims());
```
it'll print something like 
```
Dim4 { dims: [height, width, number of bytes per pixel, 1] }
```
so
```
let rgb = [
         1, 2, 3,  1, 2, 3,
         1, 2, 3,  1, 2, 3,
         1, 2, 3,  1, 2, 3,
         1, 2, 3,  1, 2, 3,
         1, 2, 3,  1, 2, 3,
         1, 2, 3,  1, 2, 3
    ];

 let tmp = Array::new(&rgb, Dim4::new(&[6, 2, 3, 1]));
```
is the same thing as loading a 2x6 pixels RGB24 image

if you try 
```
let span = Seq::default();
let r = index(&tmp, &[span, span, Seq::new(0, 0, 1)] );
let g = index(&tmp, &[span, span, Seq::new(1, 1, 1)] );
let b = index(&tmp, &[span, span, Seq::new(2, 2, 1)] );
af_print!("r = ",r);
af_print!("g = ",g);
af_print!("b = ",b);
```
r should be filled with 1, g should be filled with 2, ... but it's not the case.

I've made a small benchmark of moddims and index (your code) (GTX 970 / 40 MPixel photo / Cuda 8 / averaged values ) 
moddims => 0.065 ms
index => 0.042 ms

moddims is slower but both are quite fast

**Comment by polarathene** [comment]
@ultimaRatio The slice you create your tmp Array with, values first fill the row length which is 6, so :

```
[1, 2 , 3, 1, 2 ,3]
```
then columns(2nd dim) which you have at 2

```
[
    [1, 2 , 3, 1, 2 ,3],
    [1, 2 , 3, 1, 2 ,3]
]
```

Then the next dim which you're using for rgb values at 3:
```
[
    [
        [1, 2 , 3, 1, 2 ,3],
        [1, 2 , 3, 1, 2 ,3]
    ],
    [
        [1, 2 , 3, 1, 2 ,3],
        [1, 2 , 3, 1, 2 ,3]
    ],
    [
        [1, 2 , 3, 1, 2 ,3],
        [1, 2 , 3, 1, 2 ,3]
    ]
]
```

When you see it this way you can see that the order of the values you gave wouldn't fit into the R G B elements like you were thinking, this is red values first(basically the extracted channel like you were wanting to get as end result), then it's col/height(y position), followed by width(x position).

---

Example:

![rgb](https://cloud.githubusercontent.com/assets/5098581/26618450/8b0a360e-462e-11e7-943f-cfdde27984d2.jpg)

I'm not sure if you'll get the same values as below due to the image host possibly compressing the image again, but try a jpg of 9x9px with 3x8 red, then green, then blue. I have a 1x9 white line at the bottom. This should help visualize the pixels better.

```
[9 9 3 1]
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000 

    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000   255.0000   255.0000   255.0000     0.0000     0.0000     0.0000 
  255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000 

    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
    0.0000     0.0000     0.0000     1.0000     1.0000     1.0000   254.0000   254.0000   254.0000 
  255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000 
```
Query the red channel with the code snippet I provided earlier:

```
let r = index(&tmp, &[span, span, Seq::new(0, 0, 1)] );
af_print!("r = ",r);

// Output:
r = 
[9 9 1 1]
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  254.0000   254.0000   254.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
  255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000   255.0000 
```

---

Could you share how you're doing benchmarking/profiling for the two methods? I would like to do this to test some different approaches in my arrayfire program.

**Comment by ultimaRatio** [comment]
you're right, my example was wrong.

But since it wasn't working with the image I was loading, it means I've made an error elsewhere and I was looking at the wrong place for a wrong culprit. My bad, I apologize.

Anyway, I've stop using loadImage (for others reasons), so I could shape directly the Array and that means no need for moddims or index.

for the benchmark, it's very basic :   
```
extern crate time; // add time = "0.1" in Cargo.toml

fn main() {
    init();
    set_backend(Backend::CUDA);
    let img = load_image("2.jpg".to_string(), true);
    let span = Seq::default();
    let check_value = {
        let d = img.dims();
        d[1] as u64 * d[0] as u64
    };

    let max = 10000;
    let mut tmp = 0u64;
    let mut junk = 0i64;
    for _ in 0..max {
        let duree: u64 = time::precise_time_ns();
        let r = index(&img, &[span, span, Seq::new(0, 0, 1)]);
        let g = index(&img, &[span, span, Seq::new(1, 1, 1)]);
        let b = index(&img, &[span, span, Seq::new(2, 2, 1)]);
        tmp += time::precise_time_ns() - duree;
        junk += r.elements();
        junk += b.elements();
        junk += r.elements();
    }

    println!("index = {} ns",(tmp as f32/max as f32)/1000f32);
    println!("{} <=> {}",junk/max, check_value*3); // should be equal
}
```

the first iteration is always slow (some initializations ?), but the others runs at full speed.
first iteration : 21 ns
others : 4.5ns

**Comment by 9prady9** [comment]
Sorry for the delayed response, I wasn't working for the past couple of days.

@ultimaRatio To answer your initial question on how to extract the channels from an RGB `af::Array`, you can use indexing. However, there is a much simpler way for this use case - [slice](http://arrayfire.org/arrayfire-rust/arrayfire/fn.slice.html) to extract channels.

@polarathene The documentation link you have shared is from devel branch on the git repository. I haven't pushed this to new crate release yet - hence, the official documentation doesn't reflect this as of now. I have started adding more examples one after another and linking them in tabular format on the landing page of arrayfire-rust crates documentation - this is an ongoing effort.

To clarify from our side - `load_image` loads the image into the following layout

```
Dim4 { dims: [height, width, channels per pixel, 1] }
```
Note that the third dimension is not bytes per pixel. It is number of channels for pixel.

@ultimaRatio Yes, your observation about first run of function taking longer to run is expected behaviour. During the first run, the backend specific kernels are compiled(wherever applicable) for the current device in use and cached for subsequent runs.

**Comment by ultimaRatio** [comment]
@9prady9 : ok, thanks.
