### ISSUE TITLE
Image types supported with load_image()?

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire-rust#139]
There is quite a few formats listed on official docs, on the rust docs no format is mentioned. I've saved an image as jpg, png, bmp but only jpg would work. The other two gave the error: 

```
thread 'main' panicked at 'Error message: Unsupported operation/parameter option', /home/pola/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.3/src/error.rs:66
```

I am loading the image like this:

```
load_image("/storage/rgb.png".to_string(), true);
```

**Comment by 9prady9** [comment]
Can you please do `export AF_PRINT_ERRORS=1` and show the output of your program execution.

**Comment by ultimaRatio** [comment]
ArrayFire use FreeImage, so it should be able to open a great numbers of files : http://freeimage.sourceforge.net/features.html

have you try to use load_image_native ?

**Comment by 9prady9** [comment]
@polarathene Is this still an issue ?

**Comment by polarathene** [comment]
I've tried `load_image_native()`, same problems. The env var to show more detailed errrors has pointed out the problem though, I guess the program I used to export other formats is doing something unexpectedly making it incompatible, I'll look into if I can change that. If possible to forward such an error or mentioning in the docs that a user could have an issue with the bits per channel the image is encoded with that could be helpful :)

Code:
```
#[macro_use(af_print)]
extern crate arrayfire as af;
use af::*;

fn main() {
    let path: String = "/storage/rgb.png".to_string();
    let rgb = load_image(path.clone(), true);
    let rgb_native = load_image_native(path.clone());

    println!("RGB Dims: {:?}", rgb.dims());
    println!("RGB Native Dims: {:?}", rgb_native.dims());
}
```

Image(although png version): 
![rgb](https://cloud.githubusercontent.com/assets/5098581/26618450/8b0a360e-462e-11e7-943f-cfdde27984d2.jpg)

Error:
```
In function af_err af_load_image(void**, const char*, bool)
In file src/api/c/imageio.cpp:190
FreeImage Error: Bits per channel not supported
```

**Comment by 9prady9** [comment]
@polarathene I shall update the load_image docs about the supported bits per channel information. Sorry about the inconvenience.

**Comment by polarathene** [comment]
The bits per channel look normal, the image editor claims 8-bit Integer per channel.

**Comment by 9prady9** [comment]
load_image should be able to load alpha channels. Can you share the image ? Do you have a C++ setup where you can try loading this image using C++ API ? Ideally, that should also result in same error. Just want to eliminate the possibility of error from rust wrapper side.

**Comment by polarathene** [comment]
![rgb](https://user-images.githubusercontent.com/5098581/26927563-84bd6162-4ca6-11e7-860e-4d715eb66054.png)

Assuming the uploaded version isn't different than what I have this is the png. I do not have C++ setup for AF as I'm not a C++ dev. I'll download the uploaded png and verify the error still occurs with it.

**Comment by polarathene** [comment]
Yeah that throws an error for me. You should be able to confirm on your side too and that it is 8-bit per channel?

**Comment by ultimaRatio** [comment]
you could check the format of the image with ImageMagick : 
`identify -verbose /storage/rgb.png `

**Comment by polarathene** [comment]
`identify -verbose /storage/rgb.png`:

```
Image: /storage/rgb.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 9x9+0+0
  Resolution: 37.79x37.79
  Print size: 0.238158x0.238158
  Units: PixelsPerCentimeter
  Type: PaletteAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8/1-bit
  Channel depth:
    red: 1-bit
    green: 1-bit
    blue: 1-bit
    alpha: 1-bit
  Channel statistics:
    Pixels: 81
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 103.889 (0.407407)
      standard deviation: 126.075 (0.494413)
      kurtosis: -1.88598
      skewness: 0.369931
      entropy: 0.975119
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 103.889 (0.407407)
      standard deviation: 126.075 (0.494413)
      kurtosis: -1.88598
      skewness: 0.369931
      entropy: 0.975119
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 103.889 (0.407407)
      standard deviation: 126.075 (0.494413)
      kurtosis: -1.88598
      skewness: 0.369931
      entropy: 0.975119
    Alpha:
      min: 255 (1)
      max: 255 (1)
      mean: 255 (1)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: -nan
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 177.083 (0.694444)
      standard deviation: 117.645 (0.461355)
      kurtosis: -1.29783
      skewness: 0.840326
      entropy: -nan
  Colors: 4
  Histogram:
        24: (  0,  0,255,255) #0000FFFF blue
        24: (  0,255,  0,255) #00FF00FF lime
        24: (255,  0,  0,255) #FF0000FF red
         9: (255,255,255,255) #FFFFFFFF white
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 9x9+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    Author: Pola
    date:create: 2017-05-31T17:41:41+12:00
    date:modify: 2017-05-31T17:41:08+12:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 9, 9
    png:pHYs: x_res=3779, y_res=3779, units=1
    png:sRGB: intent=0 (Perceptual Intent)
    png:text: 2 tEXt/zTXt/iTXt chunks were found
    signature: 4a4dc3ec6ebabf72c1650e12b784c2565ed0b9d12b6858e71e1bd44b01877d4f
    Title: rgb
  Artifacts:
    filename: /storage/rgb.png
    verbose: true
  Tainted: False
  Filesize: 172B
  Number pixels: 81
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.8-6 Q16 x86_64 2017-05-20 http://www.imagemagick.org
```

It seems since I used pure RGB 255 values only, it optimized it to 1-bit channels... 
```
  Depth: 8/1-bit
  Channel depth:
    red: 1-bit
    green: 1-bit
    blue: 1-bit
    alpha: 1-bit
```

**Comment by 9prady9** [comment]
I copy pasted a portion of the output of the command `identify -verbose <name>.png`

```
 Depth: 8/1-bit
  Channel depth:
    red: 1-bit
    green: 1-bit
    blue: 1-bit
    alpha: 1-bit
......
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 9, 9
```

It is 1 bit per channel.

**Comment by polarathene** [comment]
TIL... Krita doesn't seem to have an option for preventing that, time to go raise an issue with them :)

**Comment by ultimaRatio** [comment]
try this : 
convert /storage/rgb.png png24:/storage/rgb24.png

**Comment by polarathene** [comment]
@ultimaRatio that didn't seem to work.

I raised the [issue with Krita](https://bugs.kde.org/show_bug.cgi?id=380970) team. They've noted that GIMP and Photoshop have the same behaviour, that it's apparently due to the formats standard. No idea what happens when ArrayFire creates such an image and saves to disk if it also respects that standard(I guess that is up to FreeImage?). If it does, then creating such an image with ArrayFire and then attempting to load it from disk will fail.

I believe I avoided `jpg` due to lossy format even with top quality settings not saving a 1:1 representation(some 0's became 1 and some 255 become 254 for example). Is there a lossless format that ArrayFire recommends that would support such an image? 

Alternatively I guess an issue could be raised to FreeImage to support 1-bit depth per channel pngs.. No longer an issue for me but it was an unexpected experience as to what was going on and why. Something to include in docs if there is a troubleshooting section(that the FreeImage library used to load the images does not support 1-bit depth per channel pngs(and maybe other formats), that this is apparently how such images are intended to be saved for that format and not much can really be done about it). If there isn't already, mentioning how to get the extra error information with the environment variable would also be useful.

**Comment by 9prady9** [comment]
@polarathene PNG format does work as long as the image loaded by FreeImage has 8/16/32 bit channels. We do have couple of PNG files in our repository that are being used by ArrayFire examples.

We do not handle 1-bit depth per channel images at ArrayFire level I believe, it may not be a FreeImage support issue. You can probably raise an issue on [ArrayFire](https://github.com/arrayfire/arrayfire/issues) requesting the support to load 1-bit channel PNG.

**Comment by polarathene** [comment]
@9prady9 Create an image of 0 and 255 values for the RGB channels, save this as a PNG. The Krita dev mentioned the same problem happens with GIMP and Photoshop when doing this. Instead of being able to choose an 8-bit per channel depth the png format optimizes this to 1-bit per channel. 

As mentioned earlier in this thread, FreeImage throws an error about 1-bit depth per channel pngs not being supported, thus ArrayFire fails to load the image to the GPU. I was stating that I'm not sure what happens in the reverse, ArrayFire creates an image as described and then saves it to disk(via FreeImage?), the same optimization may happen preventing ArrayFire from loading the image from disk at a later point in a users program.

**Comment by ultimaRatio** [comment]
i believe it's more a FreeImage Issue than an ArrayFire issue, and maybe more a libpng issue, since png24:rgb.png is supposed to create a RGB24 file.
you could webp  instead of png :
```
convert rgb.png rgb.webp
identify rgb.webp 
Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
```
