### ISSUE TITLE
Helloworld panics on version 3.4.3 with backend version 3.4.2.

### ISSUE THREAD

**Issue by dehn** [arrayfire/arrayfire-rust#140]
Running the helloworld example produced the following error. My laptop does not have a GPU. ArrayFire works perfectly when using C++.

Downloaded binary version of arrayfire (3.4.2) and installed in /usr/local. Setup AF_PATH etc. to include this path. 
```
$ RUST_BACKTRACE=1 cargo run --example helloworld
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/helloworld`
In function opencl::DeviceManager::DeviceManager()
In file src/backend/opencl/platform.cpp:327
OpenCL Error (-1001): Unknown OpenCL Error (-1001) when calling clGetPlatformIDs

thread 'main' panicked at 'Error message: Error either in ArrayFire or in a project upstream', src/error.rs:70
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: arrayfire::error::handle_error_general
             at ./src/error.rs:70
   8: core::ops::Fn::call
   9: arrayfire::error::HANDLE_ERROR
             at ./src/error.rs:83
  10: arrayfire::device::set_device
             at ./src/device/mod.rs:167
  11: helloworld::main
             at ./examples/helloworld.rs:8
  12: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  15: main
  16: __libc_start_main
  17: _start

```

**Comment by 9prady9** [comment]
Can you run again with `export AF_PRINT_ERRORS=1` and show us the output here.

**Comment by dehn** [comment]
Yes. I just updated the output.

**Comment by 9prady9** [comment]
Do you have any OpenCL compatible devices present on your machine ? Since you have installed ArrayFire binaries, it has all the necessary libraries for all backends, however if you don't have a compatible device, you would see error messages such as above.

If your intention was to run ArrayFire on CPU, make sure your AF_PATH doesn't have `libafopencl.so` and `libafcuda.so` in it.

**Comment by dehn** [comment]
My intention is to run ArrayFire on CPU. I use this for prototyping and then transfer my applications to GPU cluster once done.

Removing `libafcuda.so` and `libafopencl.so` from `AF_PATH` does not seem solve the issue on my machine. If I am to compile a new version of the backend which does not support CUDA and OpenCL, then it will produce version 3.5.0. This will give another kind of error.

Running ArrayFire on CPU from C++ works fine.
```
ArrayFire v3.4.2 (CPU, 64-bit Linux, build 2da9967)
[0] Intel: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 7400 MB, Max threads(4)
```

**Comment by dehn** [comment]
It works now.

Removing `libafcuda.so` and `libafopencl.so` from `AF_PATH` works. My bash did not remove the old path for arrayfire (with CUDA and OpenCL support) from LD_LIBRARY_PATH.

**Comment by dehn** [comment]
Marking issue as closed.
