### ISSUE TITLE
Improve Macros `eval` and `join_many`

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire-rust#144]

**Comment by polarathene** [comment]
Still new to macros, I have a timing macro and I'm trying to replicate the C++ example [here](https://github.com/arrayfire/arrayfire/issues/1818#issuecomment-307574205), in my timing macro it wraps the code to do the AF eval call...which is a macro. It doesn't seem happy about that though.

```Rust
use std::time::Instant;
macro_rules! my_timer {
    ($label:expr, $($thing:tt)*) => (
        for i in 0..10 {
            let start = Instant::now();
            af::eval!(
                $($thing)*
            );
            af::sync(0);
            println!("{} took: {} sec, {} ms", $label, start.elapsed().as_secs(), (start.elapsed().subsec_nanos() as f64 / 1_000_000f64) );
        };
    )
}

my_timer!("cuda locate",
        let mut idxrs = Indexer::new();
        let indices = af::locate(&bits_cuda);
        idxrs.set_index(&indices, 0, Some(true));

        index_gen(&a_cuda, idxrs);
    );
```

Error thrown: 
```
error: non-ident macro paths are experimental (see issue #35896)
```

If I don't namespace the macro instead it throws this:
```
error: no rules expected the token `mut`
```

If I skip doing eval by commenting out the macro the rest of the code runs fine as expected.

**Comment by 9prady9** [comment]
Not sure if these are the right candidates for further improvements. If anyone feels otherwise or suggestions, please reopen with the details.
