### ISSUE TITLE
lookup returns array with more dimensions than expected and redundant data

### ISSUE THREAD

**Issue by Muhd** [arrayfire/arrayfire-rust#147]
```
...
af_print!("utilities: ", utilities);
af_print!("winners: ", winners);
let lkup = &lookup(utilities, winners, 1);
af_print!("lookup: ", lkup);
...
```

Output:
```
utilities:
[20 3 1 1]
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000
    0.0000     0.6000     1.0000

winners:
[20 1 1 1]
         1
         1
         2
         2
         2
         2
         2
         1
         2
         2
         2
         2
         2
         0
         2
         2
         0
         2
         2
         2

lookup:
[20 20 1 1]
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
    0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
```
**Problem** 
Result is tiled across the selected dimension in the output, squaring the amount of space used.

**Expected**
It would be better if the result were not tiled and the result only filled n-1 dimensions where n in the number of dimensions in the input. From the above example, I would expect a 1-dimensional array (ideally oriented along the 0th dimension):
```
0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000
```

**Comment by polarathene** [comment]
It's returned 20 columns matching the indices you supplied from `winner` to the columns in `utilities`. I've not used the lookup method yet, but that doesn't look like it's broken? Perhaps you misunderstood how it works?

`&lookup(utilities, winners, 1);`
`pub fn lookup(input: &Array, indices: &Array, seq_dim: i32) -> Array`
> Given a dimension `seq_dim`, `indices` are lookedup in `input` and returned as a new Array if found

Your output is correct. You queried the 2nd dimension(cols == 1) with the `winners` supplying `indices` to the `input` array `utilities`, thus you receive a new array of 20 columns(winners values mapped to utilities columns) which contain all the rows utilities columns had.

What was it you wanted to do?

**Comment by Muhd** [comment]
I want to get a one dimensional array with the lookup values:
[0.6000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.6000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     1.0000     1.0000     0.0000     1.0000     1.0000     1.0000]

**Comment by polarathene** [comment]
`utilities` has dims `[20 3 1 1]`, 20 rows, 3 columns. All rows are tiling the first value/row in each column, is this intended? Is utilities only meant to be 3 values and not 60?

**Comment by Muhd** [comment]
Yes that is intended... perhaps I should have done random values to avoid confusion.

**Comment by polarathene** [comment]
@Muhd So when you supply indices of 0-2 you intend them to map to the columns as they currently do but also matching utilities row to the row of winners?

**Comment by 9prady9** [comment]
@Muhd The reason output's first dimension(`0`) has twenty rows is because your input has twenty rows. May I know why there are identical elements in each row ? Is that something you added intentionally using `tile` ?

As far as `lookup` is concerned it is seeing 20 rows and thus it is indexing along all those rows using the `winners` Array object.

**Comment by polarathene** [comment]
> Yes that is intended.

It's intended that the values in each column is the same? Do they ever change? If they don't you might prefer `[1,3,1,1]` for dimensions, that lookup method would work as expected then for you, you'll get a result array of `[1,20,1,1]` you can reshape that or use flat() to get `[20,1,1,1]`.

If the row values in utilities actually do vary(in which case your example is confusing if there is more than 3 possible values in utilities normally), then you can create a range() array along 1st dimension(rows == 0). Multiply that against 3, so your values will look like 0, 3, 6, 9, etc. Then add winners against that array, your example values would be 1,4,8, 11, etc, finally flatten your utilities array with flat(). Now you can index the array

```Rust
let mut indices = range(dims, 0);
indices = indices * 3;
indices += winners;
let mut idxrs = Indexer::new();
idxrs.set_index(&indices, 0, None);
let results = index_gen(&utilities, idxrs); // returns  new array of the values you indexed
```

**Comment by Muhd** [comment]
>  If they don't you might prefer [1,3,1,1] for dimensions, that lookup method would work as expected then for you, you'll get a result array of [1,20,1,1] you can reshape that or use flat() to get [20,1,1,1].

Oh, that works actually, and now I understand what lookup is actually doing. The "tiling" is a feature—it just didn't make sense in the way I wanted to use it. I still feel that it would be nice to have a more direct way to do what I was suggesting initially, in the case where the utilities array is full of independent and random values, but if I ever need that I'll try your second solution.
