### ISSUE TITLE
&mut support?

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire-rust#155]
```
// permutations_af: &mut af::Array
permutations_af = &mut shiftl(&permutations_af, &8, true); // permutations_af <<= 8

error[E0277]: the trait bound `&mut arrayfire::Array: arrayfire::arith::Convertable` is not satisfied
the trait `arrayfire::arith::Convertable` is not implemented for `&mut arrayfire::Array`
```

This seems to work so far(still working on fixing compiler errors as I've moved my code into structs/functions):

```
*permutations_af = shiftl(&*permutations_af, &8, true); 
```

**Comment by 9prady9** [comment]
@polarathene Each rust function delegates the call to C API and the `const` qualifier on C API is translated to `&Array` (immutable reference in correspondence to the `const`ness of the C API's af_array) input in rust API. If there is a variable of type `&mut Array`, you can always deref it and pass a immutable reference which is the following is working for you.
```*permutations_af = shiftl(&*permutations_af, &8, true); ```

When a mutable reference is passed, that indicates the possibility of modification in the referred object. In the case of `shiftl` or most of the other functions, unless the function is carrying out in-place modification of Array such as [cholesky_inplace](http://arrayfire.org/arrayfire-rust/arrayfire/fn.cholesky_inplace.html), accepting an immutable reference conveys the right semantics given the context.
