### ISSUE TITLE
Cannot get join to work...

### ISSUE THREAD

**Issue by Muhd** [arrayfire/arrayfire-rust#163]
af_print!("mean1: ", mean1);
    af_print!("max: ", max);
    let mean1max = &join(0, mean1, max); // note: also tried with &join(1, mean1, max) and same result

Produces:

    mean1:
    [10 1 1 1]
        0.6503
        0.5258
        0.4585
        0.4492
        0.3626
        0.5375
        0.7091
        0.2010
        0.6620
        0.1955

    max:
    [10 1 1 1]
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000
        1.0000

    thread 'main' panicked at 'Error message: One of the function arguments is incorrect', C:\Users\Muhd\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.3\src\error.rs:66
    stack backtrace:
       0:           0x45a152 - std::sys_common::backtrace::_print::hd6646a2841afdf9b
       1:           0x46bb15 - std::panicking::default_hook::{{closure}}::hbbbf077a121e5ce5
       2:           0x46b64d - std::panicking::default_hook::hf4cec78e7221fdb3
       3:           0x46bf95 - std::panicking::rust_panic_with_hook::hc0f8ec5813a243ba
       4:           0x46be16 - std::panicking::begin_panic::h9d4cce4d17a687b5
       5:           0x46bd89 - std::panicking::begin_panic_fmt::h066675d7a718e379
       6:           0x4190e8 - arrayfire::error::handle_error_general::hb420e369cd4c39c0
                                   at C:\Users\Muhd\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.3\src/error.rs:66
       7:           0x40d738 - core::ops::Fn::call::h354333d3bcae6a34
                                   at C:\projects\rust\src\libcore/ops.rs:2531
       8:           0x4191da - arrayfire::error::HANDLE_ERROR::ha53f66528e3f14ad
                                   at C:\Users\Muhd\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.3\src/error.rs:79
       9:           0x416272 - arrayfire::data::join::hba9772818d5a2759
                                   at C:\Users\Muhd\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.3\src\data/mod.rs:320
      10:           0x4089d4 - rusty_vote::normalize_ballot::h08dc81bc04b44da1
                                   at C:\Users\Muhd\IdeaProjects\rusty_vote\src/main.rs:158
      11:           0x408374 - rusty_vote::get_adversary_ballots_combined::h5e51355103c5ac78
                                   at C:\Users\Muhd\IdeaProjects\rusty_vote\src/main.rs:128
      12:           0x406ceb - rusty_vote::main::hc960c1035c5be6f3
                                   at C:\Users\Muhd\IdeaProjects\rusty_vote\src/main.rs:62
      13:           0x46f4f8 - _rust_maybe_catch_panic
      14:           0x46c6ca - std::rt::lang_start::h9fb2fbde5fcf1da2
      15:           0x408dfa - main
      16:           0x4013e7 - _tmainCRTStartup
      17:           0x40151a - mainCRTStartup
      18:         0x775b59cc - unit_addrs_search
    error: process didn't exit successfully: `target\debug\rusty_vote.exe` (exit code: 255)

**Comment by pavanky** [comment]
@Muhd Are they the same type? 

@9prady9 Whenever there is an error in any language wrapper, both `af_get_last_error` and `af_err_to_string` should be called and the appropriate message should be shown. 

This particular error message is not very useful.

**Comment by 9prady9** [comment]
The current implementation of error reporting in rust wrapper works as follows.

1. Any function call at rust level doesn't do any argument validation other than what rust provides automatically to any native function - This can be improved I guess by adding checks, but that will add redundant checks at rust level and increase code maintenance cost.
2. The call to the native library API is wrapped in unsafe block that panics whenever the library call returns an error code that is not 0(`AF_SUCCESS`).
3. For any non-zero error code from native library call, the enum's corresponding error message, which is definitely generic and is only a pointer in the right direction, is printed out.

One feature, which is currently a WIP, that can help this area is [Typed Arrays](https://github.com/arrayfire/arrayfire-rust/issues/98).

@Muhd All environment variables mentioned in [this](http://arrayfire.org/docs/configuring_environment.htm) tutorial are also applicable to rust wrapper. The one you might find useful here is [`AF_PRINT_ERRORS`](http://arrayfire.org/docs/configuring_environment.htm#af_print_errors). In your case, the reason for error  could be just that the arrays are of two different types. It looks like one is created from some random number generator function and the other is from constant. Please make sure the arrays of same type.

**Comment by pavanky** [comment]
> For any non-zero error code from native library call, the enum's corresponding error message, which is definitely generic and is only a pointer in the right direction, is printed out.

@9prady9 This is OK, but I was suggesting that additional info can be given so that `AF_PRINT_ERRORS` is not necessary. If you additionally print out the info from `af_get_last_error`, you will get the same errors we see in C++.

**Comment by 9prady9** [comment]
@pavanky Sure, I have created an issue for this. https://github.com/arrayfire/arrayfire-rust/issues/164 
@Muhd Is your issue resolved ?

**Comment by Muhd** [comment]
Yes, thank you.
