### ISSUE TITLE
Docs.rs contains invalid links

### ISSUE THREAD

**Issue by pravic** [arrayfire/arrayfire-rust#170]
In particular, the Tutorials section: https://docs.rs/arrayfire/3.5.0/arrayfire/#tutorials

**Comment by 9prady9** [comment]
@pravic I am not sure docs.rs works. The current hyperlinks for the tutorial sections use relative paths. They work as expected in the documentation we hosted via github pages. 

http://arrayfire.org/arrayfire-rust/arrayfire/index.html

**Comment by 9prady9** [comment]
We have [separate script ](https://github.com/arrayfire/arrayfire-rust/blob/master/generate_docs.sh) that runs rustdoc on standalone markdown files. We use the output files from previous step along the main documentation. I think whatever `docs.rs` process that generated documentation for our project didn't do this and thus those links are broken on the docs hosted by `docs.rs`. [Our documentation ](http://arrayfire.org/arrayfire-rust/arrayfire/index.html)looks good.

**Comment by pravic** [comment]
> Our documentation looks good.

Yes, I saw it.

> The current hyperlinks for the tutorial sections use relative paths.

May be it is better to make them absolute, at least in the root `lib.rs` to make it less confusing?

Anyway, I just wanted to stop by and tell you about it :)

**Comment by 9prady9** [comment]
We definitely appreciate your feedback.

I can make them aboslute but that will make docs.rs documentation point back to our ghpages documentation. I am not sure whether that is good or bad in web world. Do you have any idea how `docs.rs` generates the documentation ? Is it documented anywhere ?

**Comment by pravic** [comment]
No, unfortunately I can't help you. But you can ask at https://github.com/onur/docs.rs

Personally, I would prefer an absolute link rather than 404.

**Comment by 9prady9** [comment]
@pravic I have addressed this differently couple of days ago. I have refactored tutorials to use mdbook and just hyperlinking in the main documentation. 

http://arrayfire.org/arrayfire-rust/arrayfire/index.html

> Please go through our [tutorials](http://arrayfire.org/arrayfire-rust/arrayfire/book/index.html) book for more explanations on how to use ArrayFire to speedup your code.

I have also added the following to cargo.toml
```toml
[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./scripts/mathjax.script", ]
```

Docs.rs shouldn't have any issue generating the documentation now.

**Comment by 9prady9** [comment]
All issues related to docs-rs documentation generation are fixed now. the mdbook is being redirected to the one hosted on our gh-pages.
