### ISSUE TITLE
Unit tests of library crate using arrayfire crate fails

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire-rust#180]
Reported on slack channel by Victor Tashkov.

`arrayfire-rust` crate if used by an executable project , seems to work just fine. However, if used by a library crate from it's own unit tests, the tests fail to finish successfully.

The user is using actually PyCharm with rust plugin, similar to using IntelliJ IDEA with rust. The results are similar from command line project. 

OS: Windows

**Comment by vtashkov** [comment]
The actual failure message I've got is 
> WGL: Failed to clear current context

The test does almost nothing to do with the library, it just invokes info() .
The whole point is just to use(link/build) the arrayfire-rust inside my own library crate.

**Comment by 9prady9** [comment]
@vtashkov Here is what I have tried.

With `arrayfire` as dev-dependency in cargo toml file and `af::info` call inside a test, neither a bin crate nor a lib crate is giving me an issue. Both version seems to be executing fine.

I used Rust 1.30.1 MSVC toolchain on Windows 10 Pro. I ran all commands from Windows powershell.

Which version of rust did you use ?

**Comment by 9prady9** [comment]
@vtashkov Is this still an active issue ?

**Comment by vtashkov** [comment]
It depends on your criteria. ArrayFire doesn't work when you execute it simultaneously. Rust unit tests by default are run in parallel. Therefore, tests in Rust language that use ArrayFire do not work. Of course, you can say that there is an easy workaround - just use single thread.

**Comment by 9prady9** [comment]
Let me look into it once again. I don't remember if I tried two tests using
test attribute hint. I thought I did and it worked. Anyway, will check
again.

**Comment by 9prady9** [comment]
@vtashkov 

I am fraid whatever it is you are experiencing, it is specific to your development setup.

I unable to replicate the issue with rust wrapper using arrayfire `v3.6` branch on Windows. 

If this issue is present in 3.6.1 release of ArrayFire, looks like it is fixed in lastest master and v3.6 branch. We will soon being doing a 3.6.2 release of ArrayFire and you can probably try your code with rust wrapper against arrayfire 3.6.2.

For future reference, I have added the code to reproduce the issue and the output I see on windows using opencl backend(a successfull run of the program without any issue)

#### Code
```rust

#[cfg(test)]
mod tests {

    extern crate arrayfire as af;

    use self::af::*;

    #[test]
    fn it_works1() {
        set_device(0);
        info();
        assert_eq!(2, 2);
    }

    #[test]
    fn it_works2() {
        set_device(0);
        info();
        assert_eq!(2, 2);
    }
    
    #[test]
    fn it_works3() {
        set_device(0);
        info();
        let num_rows: u64 = 5;
        let num_cols: u64 = 3;
        let dims = Dim4::new(&[num_rows, num_cols, 1, 1]);
        let a = constant::<f32>(1.0,dims);
        af_print!("Create a 5-by-3 matrix of random floats on the GPU", a);
        assert_eq!(2,2);
    }

    #[test]
    fn it_works4() {
        set_device(0);
        info();
        let num_rows: u64 = 5;
        let num_cols: u64 = 3;
        let dims = Dim4::new(&[num_rows, num_cols, 1, 1]);
        let a = constant::<f32>(1.0,dims);
        af_print!("Create a 5-by-3 matrix of random floats on the GPU", a);
        assert_eq!(2,2);
    }
}
```
Output when there is no issue. If there is a problem, the above code usually segfaults.
```bash
PS > cargo build
   Compiling libcrate v0.1.0 (E:\gitroot\RustWorkspace\libcrate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
PS > cargo test
   Compiling libcrate v0.1.0 (E:\gitroot\RustWorkspace\libcrate)
    Finished dev [unoptimized + debuginfo] target(s) in 1.58s
     Running target\debug\deps\libcrate-2f0073da364bcc95.exe

running 4 tests
ArrayFire v3.6.1 (OpenCL, 64-bit Windows, build b443e146)
[0] NVIDIA: GeForce GTX 1060 3GB, 3072 MB
ArrayFire v3.6.1 (OpenCL, 64-bit Windows, build b443e146)
[0] NVIDIA: GeForce GTX 1060 3GB, 3072 MB
ArrayFire v3.6.1 (OpenCL, 64-bit Windows, build b443e146)
[0] NVIDIA: GeForce GTX 1060 3GB, 3072 MB
test tests::it_works1 ... ArrayFire v3.6.1 (OpenCL, 64-bit Windows, build b443e146)
[0] NVIDIA: GeForce GTX 1060 3GB, 3072 MB
ok
Create a 5-by-3 matrix of random floats on the GPUtest tests::it_works2 ...
[okCreate a 5-by-3 matrix of random floats on the GPU

[5 3 1 15 3 1 1]
]
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000
    1.0000     1.0000 1.0000     1.0000     1.0000
    1.0000     1.0000 1.0000
    1.0000     1.0000
    1.0000     1.0000     1.0000

1.0000 test tests::it_works3 ...     1.0000ok


test tests::it_works4 ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests libcrate

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by 9prady9** [comment]
@vtashkov Did you get a chance to check your code against latest 3.6.2 release binary of ArrayFire ?

**Comment by 9prady9** [comment]
@vtashkov Did you get a chance to check against latest release ?

**Comment by vtashkov** [comment]
No, I am sorry, I lost interest in the project. Will let you know if I try it in the future, but for now you are on your own,

**Comment by 9prady9** [comment]
Sorry to hear that. Please do leave feedback if possible. I will close this issue for now as I am unable to reproduce this on my end. If you do revisit, feel free to reopen this issue if you still facing problems similar to this issue.
