### ISSUE TITLE
Examples crash on Mac OS X

### ISSUE THREAD

**Issue by michael-p** [arrayfire/arrayfire-rust#181]
Dear all,

I installed Arrayfire using the official installer, verified that the C++ helloworld example works (including OpenCL support), but now when I try to run any of the Rust examples I get various crashes (Segmentation fault, Illegal instruction, Abort trap).
For instance, running the helloworld example in Release-mode with `AF_PRINT_ERRORS=1`:
```
ArrayFire v3.6.2 (OpenCL, 64-bit Mac OSX, build dc38ef13)
[0] APPLE: Intel(R) Iris(TM) Graphics 6100, 1536 MB
Info String:
ArrayFire v3.6.2 (OpenCL, 64-bit Mac OSX, build dc38ef13)
[0] APPLE: Intel(R) Iris(TM) Graphics 6100, 1536 MB
Arrayfire version: (3, 6, 2)
Name: Intel(R)_Iris(TM)_Graphics_6100
Platform: OpenCL
Toolkit: Apple
Compute: 1.2
Revision: dc38ef13
Indices 
[3 1 1 1]
    1.0000 
    2.0000 
    3.0000 

... some more output that looks fine...

a(indices, seq(0, 2, 1))
[3 3 1 1]
    0.0278     0.2864     0.3712 
    0.9806     0.3410     0.3543 
    0.2126     0.7509     0.6450 

Fourier transform the result
af(911,0x7fff7cfe5000) malloc: *** error for object 0x7f9eac95c978: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
``` 
With `AF_PRINT_ERRORS=1 AF_DISABLE_GRAPHICS=1 AF_MEM_DEBUG=1` it gets a bit further but still crashes eventually:
```
ArrayFire v3.6.2 (OpenCL, 64-bit Mac OSX, build dc38ef13)
[0] APPLE: Intel(R) Iris(TM) Graphics 6100, 1536 MB
Info String:
ArrayFire v3.6.2 (OpenCL, 64-bit Mac OSX, build dc38ef13)
[0] APPLE: Intel(R) Iris(TM) Graphics 6100, 1536 MB
Arrayfire version: (3, 6, 2)
Name: Intel(R)_Iris(TM)_Graphics_6100
Platform: OpenCL
Toolkit: Apple
Compute: 1.2
Revision: dc38ef13
Indices 
[3 1 1 1]
    1.0000 
    2.0000 
    3.0000 

... more output that looks fine...

a(indices, seq(0, 2, 1))
[3 3 1 1]
    0.0278     0.2864     0.3712 
    0.9806     0.3410     0.3543 
    0.2126     0.7509     0.6450 

Fourier transform the result

[5 3 1 1]
         (9.2004,0.0000)          (9.7207,0.0000)          (9.7921,0.0000) 
         (-0.2486,-0.3285)          (-0.0895,0.3153)          (-0.2429,0.5876) 
         (0.8120,0.6116)          (0.2852,-0.2623)          (-0.5090,0.0290) 
         (0.8120,-0.6116)          (0.2852,0.2623)          (-0.5090,-0.0290) 
         (-0.2486,0.3285)          (-0.0895,-0.3153)          (-0.2429,-0.5876) 

Grab last row & col of the random matrix

[5 3 1 1]
Segmentation fault: 11
```
Running exact same command again:
```
... same output as above...
8 constant array
[5 3 1 1]
         1          1          1 
         1          1          1 
         1          1          1 
         1          1          1 
         1          1          1 

Is u8_cnst array float precision type ? false
Bus error: 10
```

Rust version: `rustc 1.31.0 (abe02cefd 2018-12-04)`
Environment variables:
```
export AF_PATH=/opt/arrayfire
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$AF_PATH/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$AF_PATH/lib
```
Note that just setting `LD_LIBRARY_PATH` as recommended in Readme does not work as it cannot find the library `libglbindings`, for instance running the **C++** example (which otherwise works fine) without DYLD_LIBRARY_PATH set:
```
dyld: Library not loaded: /usr/local/opt/glbinding/lib/libglbinding.2.dylib
  Referenced from: /opt/arrayfire/lib/libafopencl.3.dylib
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by 9prady9** [comment]
@michael-p I will correct the README to use DYLD path for OSX.

As far as the crash goes, unfortunately I do not have a Intel Integrated card to test this. Similar segfaults are not happening on AMD cpu or NVIDIA GPU. I think it is OpenCL graphics related issue but I can't say for sure without proper testing. Do you have any other OpenCL capable device on your OSX system where you run the examples ?

**Comment by michael-p** [comment]
Sadly not, no. Is there a way to tell it to use the CPU based backend instead of the OpenCL one?

The thing that I find interesting is that the C++ demo works just fine. If the problem really was due to bad/broken OpenCL drivers I would have expected the C++ example to fail as well, but that one is totally fine.
Do you have any further ideas about how I could debug this?

**Comment by michael-p** [comment]
I just tried a really minimal example:
```rust
fn main() {
    print!("Info String:\n{}", af::info_string(true));
}
```
and ran that using the CPU backend, but still got a Segmentation fault:
```
$ AF_PRINT_ERRORS=1 AF_OPENCL_DEVICE_TYPE=CPU AF_SHOW_LOAD_PATH=1 cargo run
Using libafcpu.3.dylib
Using libafopencl.3.dylib
Info String:
ArrayFire v3.6.2 (OpenCL, 64-bit Mac OSX, build dc38ef13)
[0] APPLE: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz, 8192 MB
Segmentation fault: 11
```

**Comment by 9prady9** [comment]
Yes, you can use [set_backend](http://arrayfire.org/arrayfire-rust/arrayfire/fn.set_backend.html) to change the backend before calling any arrayfire functions.

The way you tried using environment variables, that actually didn't run on CPU backend.

I am not sure what's going until I can replicate it somewhere. It seems to be failing at random points from you issue description or is it failing always while one particular function ?

**Comment by michael-p** [comment]
Yes it fails at random points. But also this minimal example (with CPU) fails with Segmentation fault, even though it's not doing any real work:
```rust
extern crate arrayfire as af;

fn main() {
    af::set_backend(af::Backend::CPU);
    print!("Info String:\n{}", af::info_string(true));
}
```
Same thing when choosing `af::Backend::OPENCL`, but interestingly, when I try `af::Backend::CUDA` (which cannot work since I do not have a Nvidia card) I get a message telling me that it could not find the library as expected and then `Illegal instruction: 4`.

I also just tried compiling Arrayfire from source but everything's still the same.

**Comment by michael-p** [comment]
Closing this as there's probably not much you (or I) can do about this (probably some weird issue with the driver or linked libraries).
