### ISSUE TITLE
Why is the FloatingPoint trait private?

### ISSUE THREAD

**Issue by dchammond** [arrayfire/arrayfire-rust#182]
I am trying to write a generic library on top of arrayfire-rust. For most `Array::*` functions, having `T: arrayfire::HasAfEnum` is enough but for functions like `arrayfire::dot`, that has the additional bound of `FloatingPoint`, I cannot write a wrapping function since that trait is implemented in `utils` but `utils` is a private module.

Is there a reason this is the case?

**Comment by 9prady9** [comment]
@dchammond I have fixed this in https://github.com/arrayfire/arrayfire-rust/pull/188 can you please test the changes and let me know if that fixed the problem for you. Thank you.
