### ISSUE TITLE
Comparison operations return incorrect array type

### ISSUE THREAD

**Issue by vadixidav** [arrayfire/arrayfire-rust#185]
In the code for macro `overloaded_binary_func` [here](https://github.com/arrayfire/arrayfire-rust/blob/ea5759478a5bb15846de0f5c668affb644f818ee/src/arith/mod.rs#L304) the trait bound is present:

```rust
where A: HasAfEnum + ImplicitPromote<B>,
        B: HasAfEnum + ImplicitPromote<A>,
        <A as ImplicitPromote<B>>::Output: HasAfEnum
```

The macro then is used for comparison operators:

```rust
overloaded_binary_func!("Perform `less than` comparison operation", lt, lt_helper, af_lt);
overloaded_binary_func!("Perform `greater than` comparison operation", gt, gt_helper, af_gt);
overloaded_binary_func!("Perform `less than equals` comparison operation", le, le_helper, af_le);
overloaded_binary_func!("Perform `greater than equals` comparison operation", ge, ge_helper, af_ge);
overloaded_binary_func!("Perform `equals` comparison operation", eq, eq_helper, af_eq);
```

This results in the output array erroneously no longer being `Array<u8>` or `Array<bool>` (in Rust versions where bool is guaranteed to be 8 bits), and instead being the same an the input types in most scenarios. Another macro needs to be made here that specifically does comparison operations.

**Comment by 9prady9** [comment]
I thought I had it covered, I will look into it. Thank you for reporting.

**Comment by vadixidav** [comment]
@9prady9 Also consider using `bool` now thanks to [this](https://github.com/rust-lang/rust/pull/46176#issuecomment-359593446).

**Comment by 9prady9** [comment]
Size of bool wasn't guaranteed to be of 1 byte earlier and hence I avoided that. Changing to `bool` may be a much bigger change. I will try to make the shift for next release if possible.

**Comment by 9prady9** [comment]
I was mistaken about my earlier comment about bool, we are using bool wherever possible.
