### ISSUE TITLE
Missing unary_func macro invocation for af_not

### ISSUE THREAD

**Issue by tedil** [arrayfire/arrayfire-rust#191]
It seems like `arith/mod.rs` is missing an invocation of `unary_func!` for `af_not` (though I'm not sure if that's deliberate?).

**Comment by 9prady9** [comment]
@tedil That was a deliberate choice. [Array](http://arrayfire.org/arrayfire-rust/arrayfire/struct.Array.html) object implements [`Not`](https://doc.rust-lang.org/nightly/core/ops/trait.Not.html) trait

**Comment by tedil** [comment]
Ah okay. I was confused by this as it seemed somewhat inconsequential considering binary functions such as `and` are explicitly available so I was wondering why there was no `not`.

**Comment by 9prady9** [comment]
I understand your confusion. The idea is to have as much terse syntax as possible. `Not` traits allows us to do that. However, I don't think there are traits that allows us to do `Array && Array -> Array`. Hence, we had to take the function route for those.

Kindly close the issue if you feel all your queries have been addressed.

**Comment by 9prady9** [comment]
We took the traits approach where ever it was possible essentially. Please look at BitAnd, BitOr etc.
