### ISSUE TITLE
0xc000001d, STATUS_ILLEGAL_INSTRUCTION

### ISSUE THREAD

**Issue by Tzeroxik** [arrayfire/arrayfire-rust#198]
Hello, I'm using arrayfire and today I was running a project I've been working on for some months now. When running I got this error (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION).

It had never happened to me or my colleague so far, on any of the 3 computers we tested. But today it happens in all of them.

I suspect pherhaps some dependency is broken?

**Comment by 9prady9** [comment]
Whats the upstream (arrayfire) version you are using ? What is the tag/branch of arrayfire-rust you are using ?
A stack trace of the execution would also help.

**Comment by Tzeroxik** [comment]
I'll send the stack trace as soon as I can.
I'm using 3.6.0 and installed arrayfire via the (windows) installer on the arrayfire website.

**Comment by 9prady9** [comment]
So, you are using 3.6.0 tag of arrayfire-rust with arrayfire 3.6.4 that you downloaded from our website ?

**Comment by Tzeroxik** [comment]
Yes, that is correct.

**Comment by Tzeroxik** [comment]
Yes that's correct

**Comment by 9prady9** [comment]
There are couple of things that changed upstream and in the rust wrapper which probably could have resulted in this. I am going to publish a new crate in the next hour or so. You can try with the next version once it is out.

Sorry about the inconvenience.

**Comment by 9prady9** [comment]
@Tzeroxik I have published 3.6.1 crate, please check your application against that using 3.6.4 ArrayFire.

**Comment by Tzeroxik** [comment]
thanks you, I can only test it tomorow, but I'll post feedback as soon as I do.

**Comment by Tzeroxik** [comment]
Hello, switching to the new version worked for me, thanks!

**Comment by 9prady9** [comment]
@Tzeroxik Can you please tell which version of ArrayFire worked fine with rust 3.6.0 crate ?

**Comment by Tzeroxik** [comment]
It was 3.6.3 if I'm not mistaken.

**Comment by 9prady9** [comment]
Thank you, Would be useful for anyone else facing the problem in future.
