### ISSUE TITLE
Num Complex Issue

### ISSUE THREAD

**Issue by acm0055** [arrayfire/arrayfire-rust#201]
It appears that the "num" crate has restructured its code causing compile errors for more recent versions of the "num" crate. This would not be an issue if older versions of the num crate compiled with recent versions of Rust. It appears "complex" within "num" has been moved to "num_complex". This causes issues like the following.

```
error[E0599]: no method named `host` found for type `arrayfire::array::Array<std::vec::Vec<num_complex::Complex<f32>>>` in the current scope
  --> src/utils.rs:71:20
   |
71 |             res_af.host(&mut res);
   |                    ^^^^
   |
   = note: the method `host` exists but the following trait bounds were not satisfied:
           `std::vec::Vec<num_complex::Complex<f32>> : arrayfire::util::HasAfEnum`
```

This appears a simple issue of updating the "num" package within the arrayfire "cargo.toml". Then Rust's name space parsing should handle the rest. Any comment on this from others?

**Comment by acm0055** [comment]
Nevermind. I see the issue.

**Comment by acm0055** [comment]
This actually appears to still be an issue. For further reference the original issue was the I was trying to make an arrayfire array of Vec's which is clearly not possible. However, I still seemed to have the issue after fixing this.
```
error[E0277]: the trait bound `num_complex::Complex<f32>: arrayfire::util::HasAfEnum` is not satisfied
  --> src/utils.rs:54:25
   |
54 |             let stars = AF_Array::new(
   |                         ^^^^^^^^^^^^^ the trait `arrayfire::util::HasAfEnum` is not implemented for `num_complex::Complex<f32>`
   |
   = note: required by `<arrayfire::array::Array<T>>::new`
```
I have a local version compiling, but it is hacked together from before I noticed my first issue. When I have time I will try a fresh clone and minimal change. This maybe a tougher issue to fix as it might be a breaking ABI change. Thus, older code may fail to compile against the newer versions.

Can anyone else confirm that this is an issue or non-issue for them?

**Comment by 9prady9** [comment]
@acm0055 When are you exactly facing that issue ? Have you changed `num` crate version ? I built the crate locally using current master and it builds fine. I haven't changed num version recently.

**Comment by acm0055** [comment]
@9prady9 This is when interacting with another version of the num crate locally in my program compared to the one locally in the arrayfire crate. It seems like their was conflict between my version of the num crate and the one included within the arrayfire crate. I have not had time to rerun through things yet and see what issues are persisting.

**Comment by 9prady9** [comment]
That's probably it - difference in versions of num crate used by ArrayFire
create and your project.

The work around for now is to use num=0.1 in your project as well.

I will look into the issue and get back to you.

**Comment by acm0055** [comment]
@9prady9 I can confirm that downgrading my packages num_complex to 0.1 works yet causes issues with other packages that use num_complex 0.2. Can you confirm?

Should be a simple "main.rs"
```
use arrayfire::{Array, Dim4};
use num_complex::Complex;

fn main() {
   Array::new(&[Complex::new(0.0 as f32,0.0 as f32)], Dim4::new(&[1,1,1,1]));
}
```
"cargo.toml"
```
...
[dependencies]
num-complex = "0.2"
arrayfire = "3.6.1"
...
```

Then checking for these compilation errors. I have tested this locally and it presents the problem. The problem goes away if you downgrade the num-complex package to "0.1"

**Comment by 9prady9** [comment]
@acm0055 I have merged https://github.com/arrayfire/arrayfire-rust/pull/200 I have tested it on my end. Can you please verify using master in your project as well. Thank you!

**Comment by 9prady9** [comment]
I have tested this in third party example using the following
```
[dependencies]
num-complex = "0.2"
arrayfire = { git = "https://github.com/arrayfire/arrayfire-rust" }
```
and it works fine now. I am going to push a new release as soon as I can.

For any new visitors of this issue:

Please use **3.6.1** crate version of arrayfire-rust if you project uses num crate version **0.1.***
Please use **3.6.2 or later crate** versions of arrayfire-rust if you project uses num crate version **0.2**

**Comment by 9prady9** [comment]
Published a new crate version that addresses this issue
https://github.com/arrayfire/arrayfire-rust/releases/tag/v3.6.2

**Comment by acm0055** [comment]
@9prady9 I got a chance to test this on my dummy project. I have not had time to go back through and rework for things on my other project.
