### ISSUE TITLE
Fix no error message seg fault

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#211]
For example: matrix addition
```
let dims = arrayfire::Dim4::new(&[4,4,1,1]);
let a = arrayfire::randu::<f32>(dims);
let sa =  arrayfire::sparse_from_dense(&a ,arrayfire::SparseFormat::CSR);
let b = arrayfire::randu::<f32>(dims);
let sb = arrayfire::sparse_from_dense(&b ,arrayfire::SparseFormat::CSR);
let c = sb.clone() + sa.clone();
arrayfire::af_print!("Random matrix", c);
```
Results in a segmentation fault

**Comment by 9prady9** [comment]
@BA8F0D39 Can you please share the following
- Rust version
- ArrayFire binary installation version
- Rust wrapper Version
- OS

**Comment by 9prady9** [comment]
A quick update, I was able to reproduce it. I am looking into if this is lack of feature or something else. Either way, some sort of error message should have been printed instead of silent seg fault.

**Comment by 9prady9** [comment]
One thing is sure, this operation (sparse + sparse addition) is not supported 3.6.4 version of ArrayFire library which is what you seem to be using - need your confirmation on that front. Latest development branch - master - has this feature and it should be automatically available in the wrapper when our next ArrayFire release is made.

Having said, I will look into this no message seg fault however, thanks for reporting it.

**Comment by 9prady9** [comment]
@BA8F0D39 I have renamed the issue to reflect the actual issue. With the fix I made in https://github.com/arrayfire/arrayfire-rust/pull/212 you should a proper error message such as the following for your example using ArrayFire-upstream-version 3.6.4
```
thread 'main' panicked at 'Error message: Unsupported operation/parameter option
Last error: No Last Error', src/error.rs:40:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Comment by BA8F0D39** [comment]
Thanks.
I'll wait for the new arrayfire version for rust.
