### ISSUE TITLE
Feature request: create array from raw device pointers

### ISSUE THREAD

**Issue by L1AN0** [arrayfire/arrayfire-rust#225]
In C++ we can use a raw device pointer to create an arrayfire Array:

```

    // Create an array on the host, copy it into an ArrayFire 2x3 ArrayFire
    // array
    float host_ptr[] = {0, 1, 2, 3, 4, 5};
    array a(2, 3, host_ptr);
 
    // Create a CUDA device pointer, populate it with data from the host
    float *device_ptr;
    cudaMalloc((void **)&device_ptr, 6 * sizeof(float));
    cudaMemcpy(device_ptr, host_ptr, 6 * sizeof(float), cudaMemcpyHostToDevice);
 
    // Convert the CUDA-allocated device memory into an ArrayFire array:
    array b(2, 3, device_ptr, afDevice);  // Note: afDevice (default: afHost)
    // Note that ArrayFire takes ownership over `device_ptr`, so memory will
    // be freed when `b` id destructed. Do not call cudaFree(device_ptr)!
 
```

(from http://arrayfire.org/docs/gettingstarted.htm).

However, we cannot do this in the current Rust API, while this feature is very useful in practice when we want to modify existing cuda arrays.

**Comment by L1AN0** [comment]
See also https://github.com/arrayfire/arrayfire/blob/fbea2aeb6f7f2d277dcb0ab425a77bb18ed22291/include/af/array.h#L377.

**Comment by 9prady9** [comment]
@L1AN0 Sure, we can add this feature. 

When I originally started working on rust wrapper, I couldn't find much of crates that let's any user directly do CUDA programming i.e. expose the entire CUDA runtime API via a rust crate. Slowly, this scenario changed and projects like https://github.com/bheisler/RustaCUDA and https://github.com/calebwin/emu came along that lets user direct access to frameworks like CUDA / OpenCL. Hence, I postponed this feature addition.
