### ISSUE TITLE
[BUG]  Segfault error message when matmul function is used.

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#243]
Description
===========
Segfault error message when matmul function is used.

Reproducible Code and/or Steps
------------------------------

```
       let n:u64 = 1000 ;

	let a_dims = arrayfire::Dim4::new(&[n,n,1,1]);
	let a = arrayfire::randn::<f32>(a_dims);

        let b_dims = arrayfire::Dim4::new(&[n,n,1,1]);
 	let b = arrayfire::randn::<f32>(b_dims);

	let c =  arrayfire::matmul(&a, &b, arrayfire::MatProp::NONE, arrayfire::MatProp::NONE) ;
```

System Information
------------------
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build fbea2ae)
Platform: CUDA Runtime 10.1, Driver: 440.82
[0] TITAN Xp, 12195 MB, CUDA Compute 6.1
Arrayfire version: (3, 7, 0)
Name: TITAN_Xp
Platform: CUDA
Toolkit: v10.1
Compute: 6.1
Revision: fbea2ae

**Comment by 9prady9** [comment]
@BA8F0D39 Does the output change if you run your program with environment variable `AF_PRINT_ERRORS` set to 1.

You can it using `export AF_PRINT_ERRORS=1`

**Comment by BA8F0D39** [comment]
@9prady9   Why is it throwing a segment fault?

**Comment by 9prady9** [comment]
I am not sure if even the crash and code-run are related if those two events are separated by such huge time difference. How did you conclude  crash was caused by this particular run from 10 hours ago ?

**Comment by BA8F0D39** [comment]
It was the only program running on the machine. I left it overnight, when I went to sleep.
