### ISSUE TITLE
[BUG] unable to pad a corner or a side

### ISSUE THREAD

**Issue by sk4r** [arrayfire/arrayfire-rust#246]
Description
===========
https://github.com/arrayfire/arrayfire/blob/c7f16cca120f722014458696e50aa292cb803e76/test/pad_borders.cpp#L147-L159 tells me I should be able to pad a corner.

arrayfire-rust uses `af_pad` wrapper around the function being tested in that code. That wrapper checks for nonzero number of dimensions (https://github.com/arrayfire/arrayfire/blob/1405a9448f79ca56cc875f57db36cc6c33806272/src/api/c/data.cpp#L431-L432).

The problem is if begin/end padding is `&[0, 0, 0, 0]`, this line https://github.com/arrayfire/arrayfire-rust/blob/39ab7a5c49701c038846725555796d497d7d6517/src/core/data.rs#L951 tells `af_pad` that there are 0 dimensions (`begin.ndims()` calls `begin.elements()` which multiplies all 4 values and ends up being 0).

```
ArrayFire v3.7.2 (CPU, 64-bit Linux, build default)
[0] AMD: AMD Ryzen 7 2700X Eight-Core Processor
[3 3 1 1]
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000
    1.0000     1.0000     1.0000

thread 'main' panicked at 'Error message: Size is incorrect
Last error: In function af_err af_pad(void**, af_array, unsigned int, const dim_t*, unsigned int, const dim_t*, af_border_type)
In file src/api/c/data.cpp:431
Invalid dimension for argument 2
Expected: begin_ndims > 0 && begin_ndims <= 4
```

Reproducible Code and/or Steps
------------------------------

```rust
    let a = constant::<f32>(1.0, Dim4::new(&[3, 3, 1, 1]));
    print(&a);
    let begin_dims = Dim4::new(&[0, 0, 0, 0]);
    let end_dims = Dim4::new(&[2, 2, 0, 0]);
    let padded = pad(&a, begin_dims, end_dims, BorderType::ZERO);
    print(&padded);
```

System Information
------------------

Checklist
---------

- [ ] Using the latest available ArrayFire release
- [ ] GPU drivers are up to date

**Comment by sk4r** [comment]
Locally fixed like this but I wasn't sure if there's a better way so didn't submit a PR
```diff
diff --git a/src/core/data.rs b/src/core/data.rs
index 22dfc04..40bfe3e 100644
--- a/src/core/data.rs
+++ b/src/core/data.rs
@@ -948,9 +948,9 @@ pub fn pad<T: HasAfEnum>(
         let err_val = af_pad(
             &mut temp as *mut af_array,
             input.get(),
-            begin.ndims() as c_uint,
+            begin.get().len() as c_uint,
             begin.get().as_ptr() as *const dim_t,
-            end.ndims() as c_uint,
+            end.get().len() as c_uint,
             end.get().as_ptr() as *const dim_t,
             fill_type as c_uint,
         );
```

**Comment by 9prady9** [comment]
@sk4r Thank you for reporting it. Simple but yet bad one it is, sorry about the inconvenience. I didn't realize that dim4::ndims method doesn't exactly represent length of this array. What you have is also correct and but since dim4 represents size upto a maximum of 4 dimensions in this case, we can just hard code it to 4.

The fix (will be pushed to #244) for this will be available in next release.

**Comment by 9prady9** [comment]
I am going to merge the fix soon and you should be able to use master branch from your rust Cargo.toml directly even though the crate isn't published yet.

**Comment by sk4r** [comment]
Pulled the latest, thanks for the quick fix!
