### ISSUE TITLE
Mention about negative indices in rust indexing tutorial

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire-rust#257]

**Comment by mcobzarenco** [comment]
:+1: FWIW, I was not aware it's supported by arrayfire until I noticed indices are `isize`

**Comment by 9prady9** [comment]
> 
> 
> 👍 FWIW, I was not aware it's supported by arrayfire until I noticed indices are `isize`

Sorry about that, I have fixed this and should be available in next release.
