### ISSUE TITLE
[Perf] Element wise division of a 2x2 matrix takes 1 second

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#270]
Description
===========
Element wise division of a 2x2 matrix takes 1 second for each iteration, which is extremely slow.
JIT is failing too.

ArrayFire v3.7.2 (CUDA, 64-bit Linux, build 218dd2c)
Platform: CUDA Runtime 10.0, Driver: 455.45.01
[0] GeForce GTX 1060 3GB, 3019 MB, CUDA Compute 6.1
Info String:
ArrayFire v3.7.2 (CUDA, 64-bit Linux, build 218dd2c)
Platform: CUDA Runtime 10.0, Driver: 455.45.01
[0] GeForce GTX 1060 3GB, 3019 MB, CUDA Compute 6.1
Arrayfire version: (3, 7, 2)
Name: GeForce_GTX_1060_3GB
Platform: CUDA
Toolkit: v10.0
Compute: 6.1
Revision: 218dd2c

Code for division
```
	let A_dims = arrayfire::Dim4::new(&[2,2,1,1]);

	let mut A = arrayfire::randu::<f64>(A_dims)+ (0.01 as f64);
	let mut B = arrayfire::randu::<f64>(A_dims)+ (0.01 as f64);

	let var0: f64 = 0.9;
	let var1: f64 = 0.8;
	let two: f64 = 2.0;
	for i in 0..10000
	{
		let C = arrayfire::randu::<f64>(A_dims)+0.01;

		B =  (B.clone())*var1  + (1.0-var1)*arrayfire::pow(&C,&two,false);
		A = (A.clone())*var0  + (1.0-var0)*(C);

		let D = A.clone()/(1.0-var0);
		let E = B.clone()/(1.0-var1);
		let F = arrayfire::sqrt(&E) + 1.0e-8;

		let X = (D/(F  ));
		arrayfire::print_gen("X".to_string(), &X,Some(6));
	}

```

**Comment by 9prady9** [comment]
@BA8F0D39 I ran this my quickly modifying the `helloworld` in our crate and the example seems to run fine - I don't see each iteration taking like a second or anything. Can you please share the code you are using to time this.

Note: Also, 3.7.3 version has been out for a while, please upgrade to newer version if possible.

**Comment by BA8F0D39** [comment]
ArrayFire v3.7.3 (CUDA, 64-bit Linux, build 59ac7b9)
Platform: CUDA Runtime 10.2, Driver: 455.45.01
[0] GeForce GTX 1060 3GB, 3019 MB, CUDA Compute 6.1
Info String:
ArrayFire v3.7.3 (CUDA, 64-bit Linux, build 59ac7b9)
Platform: CUDA Runtime 10.2, Driver: 455.45.01
[0] GeForce GTX 1060 3GB, 3019 MB, CUDA Compute 6.1
Arrayfire version: (3, 7, 3)


```
	let A_dims = arrayfire::Dim4::new(&[2,2,1,1]);

	let mut A = arrayfire::randu::<f64>(A_dims)+ (0.01 as f64);
	let mut B = arrayfire::randu::<f64>(A_dims)+ (0.01 as f64);

	let var0: f64 = 0.9;
	let var1: f64 = 0.8;
	let two: f64 = 2.0;
	for i in 0..10000
	{
		let start_time = std::time::Instant::now();
		let C = arrayfire::randu::<f64>(A_dims)+0.01;

		B =  (B.clone())*var1  + (1.0-var1)*arrayfire::pow(&C,&two,false);
		A = (A.clone())*var0  + (1.0-var0)*(C);

		let D = A.clone()/(1.0-var0);
		let E = B.clone()/(1.0-var1);
		let F = arrayfire::sqrt(&E) + 1.0e-8;

		let X = (D/(F  ));
		arrayfire::print_gen("X".to_string(), &X,Some(6));
		println!("Elapsed time: {:.6?}", start_time.elapsed());
	}

```






X
[2 2 1 1]
    3.770490     3.718878 
    4.027615     3.804716 

Elapsed time: 841.942499ms
X
[2 2 1 1]
    3.572915     3.806746 
    3.742451     3.892724 

Elapsed time: 995.720414ms
X
[2 2 1 1]
    3.721867     3.612804 
    3.871257     3.933822 

Elapsed time: 916.768548ms
X
[2 2 1 1]
    3.845863     3.770225 
    4.013631     3.774417 

Elapsed time: 810.457573ms
X
[2 2 1 1]
    3.974589     4.079346 
    4.351963     3.920898 

Elapsed time: 828.601737ms
X
[2 2 1 1]
    4.031869     4.169822 
    4.426706     4.066968 

Elapsed time: 945.475999ms
X
[2 2 1 1]
    4.034275     4.271906 
    4.478763     4.135442 

Elapsed time: 985.011376ms
X
[2 2 1 1]
    3.440519     4.066034 
    3.490660     3.637745 

Elapsed time: 975.420433ms
