### ISSUE TITLE
Bitnot changes array type?

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#276]
Description
===========
https://arrayfire.org/arrayfire-rust/arrayfire/fn.bitnot.html

It says the output array type should match the input array type. 
If you input a bool array into bitnot, then the output becomes an integer array?

```
	let v0: [bool; 5] = [false, true, true, false, true];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[5, 1, 1, 1]));

	arrayfire::print_gen("a0".to_string(), &a0,Some(6));
	a0 = arrayfire::bitnot(&a0);
	arrayfire::print_gen("a0".to_string(), &a0,Some(6));
```

ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d99887a)
Platform: CUDA Runtime 11.1, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Info String:
ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d99887a)
Platform: CUDA Runtime 11.1, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
Name: GeForce_RTX_3090
Platform: CUDA
Toolkit: v11.1
Compute: 8.6
Revision: d99887a
a0
[5 1 1 1]
           0 
           1 
           1 
           0 
           1 

a0
[5 1 1 1]
          -1 
          -2 
          -2 
          -1 
          -2

**Comment by 9prady9** [comment]
@BA8F0D39 I am able to reproduce this on my end successfully. I am looking into it and shall post an update here once I figure out if it is the wrapper or upstream causing this. Thanks for reporting it!

**Comment by 9prady9** [comment]
As I initially suspected, this has to do with 2's complement representation of integers. 

Lets say we have 8 bit numbers:
- `true` -> `1` which on bit not will give `11111110` which is `-2` in two's complement representation. 
- `false` -> `0` which on bit not will give `11111111` which is `-1` in two's complement representation.

Thus when arrayfire's print function is printing the `b8` array to console, hence we see `-1`'s and `-2`'s for 0 and 1 in the `af_print` output.

You can see the similar behavior with integers using C++ and Rust code snippets shared below (with respective outputs shown after the code).
```c++
    bool a = true;
    bool b = false;
    bool c = ~a;
    bool d = ~b;
    printf("a (%d), b(%d)\n", a, b);
    printf("~a (%d), ~b(%d)\n", ~a, ~b);
    printf("c=~a(%d), d=~b(%d)\n", c, d);
    printf("hex of true 0x%0.8x\n", (int)a);

    int x = 0x0001;
    int y = ~x;
    printf("x 0x%0.4x\n", x);
    printf("y 0x%0.4x -- =  %d \n", y, y);
```
```bash
a (1), b(0)
~a (-2), ~b(-1)
c=~a(1), d=~b(1)
hex of true 0x00000001
x 0x0001
y 0xfffffffe -- =  -2 
```

```rust
    let a = true;
    let b = false;
    println!("a {} as integer {}", a, a as i32);
    println!("b {} as integer {}", b, b as i32);
    let c = !a;
    let d = !b;
    println!("c {} as integer {}", c, c as i32);
    println!("d {} as integer {}", d, d as i32);
    let e = 1;
    let f = !1;
    println!("e {}", e);
    println!("f {}", f);
```
```bash
a true as integer 1
b false as integer 0
c false as integer 0
d true as integer 1
e 1
f -2
```

The behavior is not from wrapper code for sure, there is no change in type of the `Array` being returned from the function call. It only appears like from the output of print function call because of the above explained reason.

The bit patterns of bitwise negated input is still valid in the output Array.

**Comment by BA8F0D39** [comment]
@9prady9 

If you use the arrayfire::locate function to check the output, arrayfire::bitnot seems to behaves weirdly.
```

	let v0: [bool; 5] = [false, true, true, false, true];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[5, 1, 1, 1]));

	arrayfire::print_gen("a0".to_string(), &a0,Some(6));

	let idx = arrayfire::locate(&a0);
	arrayfire::print_gen("idx".to_string(), &idx,Some(6));

	a0 = arrayfire::bitnot(&a0);
	arrayfire::print_gen("a0".to_string(), &a0,Some(6));

	let idx = arrayfire::locate(&a0);
	arrayfire::print_gen("idx".to_string(), &idx,Some(6));


```


ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d86edd18)
Platform: CUDA Runtime 11.2, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
Name: GeForce_RTX_3090
Platform: CUDA
Toolkit: v11.2
Compute: 8.6
Revision: d86edd18
a0
[5 1 1 1]
           0 
           1 
           1 
           0 
           1 

idx
[3 1 1 1]
           1 
           2 
           4 

a0
[5 1 1 1]
          -1 
          -2 
          -2 
          -1 
          -2 

idx
[5 1 1 1]
           0 
           1 
           2 
           3 
           4 




The first idx array should be {1,2,4} ,which is correct.

The second idx array should be {0,3} , which is incorrect.

Why does the arrayfire::locate function think the array type is u8 after executing the  arrayfire::bitnot function?

**Comment by 9prady9** [comment]
Actually, the output does make sense, let me explain. In locate(where in C++ API) implementation, all the `-1`'s and `-2`'s in the bit not output when compared to zero turn up as non-zero elements which is correct. Hence, the output of locate is showing all elements. Input isn't converted to any other type.

Given that we know `-1` is bit not result (in integer form) of zero, you can use the following work around that compares `-1` integer constant array with bit not output(`a0`) to actually locate non-zero elements.
```rust
    //JIT operation
    let nones = constant(-1, a0.dims());
    
    // JIT operation - result is true(1)/false(0) unlike earlier bit patterns
    let check_nones = eq(&a0, &nones, false);
    
    //now above two steps are enqueued for evaluation as a single kernel
    let idx = arrayfire::locate(&check_nones); 
    
    arrayfire::print_gen("idx".to_string(), &idx,Some(6));
```

Hope that helps.
