### ISSUE TITLE
[Build] serde/arrayfire conflict when building

### ISSUE THREAD

**Issue by ronniec95** [arrayfire/arrayfire-rust#279]
Description
===========
When clean build of arrayfire-rust. appears to be a conflict between serde and arrayfire 3.8

Build Environment
-----------------
Compiler version: rustc 1.49.0 (e1884a8e3 2020-12-29)
Operating system: Windows 10
Build environment: debug/release

Error Log
---------
   Compiling arrayfire v3.8.0
error[E0603]: module `export` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:28:10
    |
28  | #[derive(Deserialize, Debug)]
    |          ^^^^^^^^^^^ private module
    |
note: the module `export` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:31:5
    |
31  |     use_lib: bool,
    |     ^^^^^^^ private module
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:34:5
    |
34  |     build_type: String,
    |     ^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:35:5
    |
35  |     build_threads: u8,
    |     ^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:36:5
    |
36  |     build_cpu: String,
    |     ^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:37:5
    |
37  |     build_cuda: String,
    |     ^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:38:5
    |
38  |     build_opencl: String,
    |     ^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:39:5
    |
39  |     build_nonfree: String,
    |     ^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:40:5
    |
40  |     build_examples: String,
    |     ^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:41:5
    |
41  |     build_test: String,
    |     ^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:43:5
    |
43  |     with_intelmkl: String,
    |     ^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:44:5
    |
44  |     with_imageio: String,
    |     ^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:45:5
    |
45  |     with_graphics: String,
    |     ^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:46:5
    |
46  |     with_opencl_blas_lib: String,
    |     ^^^^^^^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:48:5
    |
48  |     vcpkg_toolchain_file: String,
    |     ^^^^^^^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:50:5
    |
50  |     lnx_cuda_sdk: String,
    |     ^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:51:5
    |
51  |     lnx_opencl_sdk: String,
    |     ^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:52:5
    |
52  |     lnx_cuda_host_compiler: String,
    |     ^^^^^^^^^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:54:5
    |
54  |     win_cuda_sdk: String,
    |     ^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:55:5
    |
55  |     win_opencl_sdk: String,
    |     ^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:56:5
    |
56  |     win_cmake_generator: String,
    |     ^^^^^^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `private` is private
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.8.0\build.rs:57:5
    |
57  |     win_vs_toolset: String,
    |     ^^^^^^^^^^^^^^ private module
    |
note: the module `private` is defined here
   --> C:\Users\mushf\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.123\src\lib.rs:277:5
    |
277 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 22 previous errors

For more information about this error, try `rustc --explain E0603`.
error: could not compile `arrayfire`

```
Any ideas how to resolve? This is a clean build 

**main.rs**
use arrayfire;
fn main() {
}
```

**Comment by 9prady9** [comment]
Do you mean `arrayfire-rust` crate itself fails to compile using arrayfire installed by our website installer ? Or is this happening in client code ?

**Comment by ronniec95** [comment]
Yes `arrayfire-rust` crate fails to compile. The arrayfire binary is clean downloaded from the website just now and installed.

Clean build of a test project

Cargo.toml

```
[package]
edition = "2018"
name = "test"
version = "0.1.0"
[dependencies]
arrayfire = "^3.8"

```

Just now tried with `rustc1.50 `- same issue

It looks like it related to a conflict in the build.rs where serde_derive and arrayfire are both defining export/private?

**Comment by 9prady9** [comment]
Let me try using this from different bin crate. The crate itself seems to be building fine for me on Windows.

**Comment by ronniec95** [comment]
Hi I found the issue
A cargo clean/build doesn't remove the `Cargo.lock` file.

Removing `Cargo.lock` and rebuilding fixes the problem. Or doing a `cargo-update` first

I thought Rust semver would keep each crate separate. The semver isolation appears to break on the build.rs step?

**Comment by 9prady9** [comment]
Glad you found the problem. I just finished using the crate from bin crate and it worked fine.

Personally, I didn't encounter this problem earlier today or couldn't replicate it either. Wonder what are the exact sequence of steps that lead to this

**Comment by ronniec95** [comment]
I've managed to build a minimum test case.

The follow Cargo.toml files have a single difference for serde_derive (v0.118) vs (0.123). Other libs, which were part of my larger project, don't appear to make a difference.

[cargo_toml.zip](https://github.com/arrayfire/arrayfire-rust/files/5967484/cargo_toml.zip)

Hope this helps.

**Comment by 9prady9** [comment]
All mentions of `serde` in ArrayFire has `1.0` as requirement with no patch number in semver notation. I would think rust logic would pick matching semver across all involved instances of serde_derive. I am not sure how how arrayfire's inclusion is resulting into this conflict. Someone with more intimate knowledge of how cargo works would be a better guide in this scenario I think.

**Comment by ronniec95** [comment]
Agreed. The cargo.toml file just says serde-derive="^1" but cargo won't
update from 1.0.118 to 1.0.123 automatically without a call to `cargo
update`. The major number is the same in both cases

Sure push it to cargo Devs.
