### ISSUE TITLE
Use the unified API and switch backends at runtime

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-rust#29]
Now that the unified API is in the devel branch, the choice of backend can be made at runtime via a specified command.

I think this needs to be done after a particular tag is made that is compatible with 3.0. We can skip 3.1 compatibility entirely and jump to 3.2.

**Comment by 9prady9** [comment]
@pavanky As of now, we will keep it at 3.1 tag and update the tag as we progress towards 3.2
