### ISSUE TITLE
arrayfire::set_rows fails on bool array? [BUG]

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#295]
Description
===========

```

	let v0: Vec<bool>  = vec![true, true, true, true, true, true];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[v0.len() as u64, 1, 1, 1]));

	arrayfire::print_gen("a0".to_string(), &a0, Some(6));

	let v1: Vec<bool>  = vec![false, false];
	let mut a1 = arrayfire::Array::new(&v1, arrayfire::Dim4::new(&[v1.len() as u64, 1, 1, 1]));

	arrayfire::set_rows(&mut a0, &a1, 2, 3);

	arrayfire::print_gen("a0".to_string(), &a0, Some(6));

```

Info String:
ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d99887ae)
Platform: CUDA Runtime 11.1, Driver: 465.19.01
[0] NVIDIA GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
Name: NVIDIA_GeForce_RTX_3090
Platform: CUDA
Toolkit: v11.1
Compute: 8.6
Revision: d99887ae
a0
[6 1 1 1]
           1 
           1 
           1 
           1 
           1 
           1 

thread 'main' panicked at 'Error message: Size is incorrect
Last error: In function af_err af_assign_seq(void**, af_array, unsigned int, const af_seq*, af_array)
In file src/api/c/assign.cpp:184
Invalid dimension for argument 0
Expected: (outDims.ndims() >= (dim_t)ndims)
 0# af_assign_seq in /lib/libafcuda.so.3
 1# af_assign_seq in /lib/libaf.so.3

**Comment by 9prady9** [comment]
@BA8F0D39 I found the problem, it is in the wrapper call. Will send in a fix soon.
