### ISSUE TITLE
[BUG] Add MatchType support info for match_template in documentation

### ISSUE THREAD

**Issue by duducv** [arrayfire/arrayfire-rust#302]
arrayfire: 3.8.0;
OS: Windows;
cmd operation: Cargo build;

I'm trying to use a function match_template,  however when I choose matchType ::SHD or matchType ::NCC
the compiler closes with the following error:

thread 'main' panicked at 'Error message: One of the function arguments is incorrect
Last error: In function af_err __cdecl af_match_template(void **,void *const ,void *const ,const af_match_type)
In file src\api\c\match_template.cpp:42
Invalid argument at index 3
Expected: (m_type >= AF_SAD && m_type <= AF_LSSD)
 0# af::array::host in afcuda
 1# af::array::host in afcuda
 2# af::array::host in af

**Comment by 9prady9** [comment]
@duducv Sorry about the inconvenience. Not all error metrics are implemented for image comparison. SHD and NCC are one of them. Hence, the message indicates the same. This is the current limitation in upstream.

I am changing the issue title to change the docs to reflect the limitation.
