### ISSUE TITLE
[BUG]Typo in readme for MacOS

### ISSUE THREAD

**Issue by pauleaster** [arrayfire/arrayfire-rust#303]
Description
===========
Change readme line:
`On OSX: do export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$AF_PATH/lib64`
To:
`On OSX: do export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$AF_PATH/lib`

After installing arrayfire 3.7.2, the installation directory was `/opt/arrayfire` and the library files were in the `./lib` subdirectory.

**Comment by 9prady9** [comment]
Thank you for reporting this!
