### ISSUE TITLE
[BUG] FFT example not working, Trait Bound HasAfEnum not implemented for Complex<float>

### ISSUE THREAD

**Issue by stexa** [arrayfire/arrayfire-rust#331]
Can not run the fft example: the trait `HasAfEnum` is not implemented for `Complex<{f64}>`.

Using:
- MacOS x86_64
- rustc version 1.62.1 
- rust edition 2021
- arrayfire 3.8
- num 0.4.0

The documentation of this library is saying that HasAfEnum is implemented for Complex< f32 > and Complex< f64 >.

<img width="828" alt="Screenshot 2022-08-08 at 14 52 53" src="https://user-images.githubusercontent.com/93521519/183422522-adbc764d-daaf-46e7-a58a-51a0ff5c7149.png">

**Comment by cavemanloverboy** [comment]
I'm also seeing this

**Comment by 9prady9** [comment]
@stexa Please see the implementations here https://github.com/arrayfire/arrayfire-rust/blob/89528902409a849ee92c982d19024789112e510c/src/core/util.rs#L210-L241. 

I am unable to reproduce this using `master` branch. Are you noticing this with release version of crate or master branch ?

**Comment by 9prady9** [comment]
@stexa Is still an active issue on your end ?

**Comment by stexa** [comment]
It is resolved! Was not working with 3.8 from crates.io, but it is working when adding arrayfire from git master branch.
`
[dependencies]
arrayfire = { git = "https://github.com/arrayfire/arrayfire-rust" }
num = "0.4.0"
`

**Comment by 9prady9** [comment]
> It is resolved! Was not working with 3.8 from crates.io, but it is working when adding arrayfire from git master branch. `[dependencies] arrayfire = { git = "https://github.com/arrayfire/arrayfire-rust" } num = "0.4.0"`

Thanks for clarifying, I will try to push our a new crate soon. Sorry about the inconvenience.
