### ISSUE TITLE
How to convert Seq to Array?

### ISSUE THREAD

**Issue by 3togo** [arrayfire/arrayfire-rust#332]
In c++, convert seq to array is very simple and is shown as following:

seq s(10, 20, 2);   // [10, 20, 2] => 10, 12, 14....20
array arr = s;
af_print(arr);      // 10    12    14    16    18    20

However, how to do the same in arrayfire-rust?

Eli

**Comment by 9prady9** [comment]
@3togo I believe there is no direct syntactic form like the C++ wrapper of ArrayFire. However, you can easily implement one by doing the following

```rust
let r = range(seq_len);
let sa = seq_begin + seq_step * r;
```

Please note that the above is only for quick illustration, kindly refer to  - [C++ code](https://github.com/arrayfire/arrayfire/blob/master/src/api/cpp/seq.cpp#L77-L86) for the exact logic.

**Comment by 3togo** [comment]
many thanks
