### ISSUE TITLE
How to do assignment?

### ISSUE THREAD

**Issue by 3togo** [arrayfire/arrayfire-rust#333]
In c++, assignment will look something like this.

    array reference = A(span, 2);
    A(span, 2) = 3.14f;
    assert(allTrue<bool>(reference != A(span, 2)));

How to do it in rust version?

**Comment by 9prady9** [comment]
please check https://arrayfire.org/arrayfire-rust/book/indexing.html

**Comment by 3togo** [comment]
@9prady9 
many thanks again
