### ISSUE TITLE
Pad invert

### ISSUE THREAD

**Issue by HVisMyLife** [arrayfire/arrayfire-rust#369]
Is there any way to "invert" arrayfire::pad? So instead of adding borders, I want to "cut" them. 
Even better would be wrap mode for convolution, because that is what I'm trying to do.
Thanks in advance

**Comment by 9prady9** [comment]
Perhaps https://arrayfire.org/arrayfire-rust/book/indexing.html is what you are looking for. Can you please share an illustrative example to show what you are trying to accomplish
