### ISSUE TITLE
Feature Update Arrayfire Rust to 3.9.0

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#375]
Description
===========
Update Arrayfire Rust to match Arrayfire Release 3.9.0

**Comment by BA8F0D39** [comment]
@9prady9

**Comment by 9prady9** [comment]
@BA8F0D39 thank you, will take care of it by end of this week.

**Comment by 9prady9** [comment]
@BA8F0D39 I am sorry, I couldn't get to it. Give me some more time, I will take care of it

**Comment by BA8F0D39** [comment]
@9prady9 
Everything in the master branch of arrayfire rust seems to work with 3.9.0 except that it doesn't have OneAPI backend support for A770 16GB

**Comment by 9prady9** [comment]
I am extremely sorry for the delay on my end, post my earlier message - I had to under go an immediate minor surgery to my left hand. I am better now, will attend to this ticket this weekend. Or at the least provide an update here on what is the plan for adding oneAPI support.

**Comment by 9prady9** [comment]
Will address this via different workflow, trying out github projects.

**Comment by stevefan1999-personal** [comment]
Is there any progress over this? I'm curious to use this on for company who needs SPMM and LU reduction
