### ISSUE TITLE
n-dimensional Arrays

### ISSUE THREAD

**Issue by MichaelHirn** [arrayfire/arrayfire-rust#44]
The documentation states
> Currently, Array objects can store only data until four dimensions

I would like to learn more about why that is and if there are plans to make it store any kind of n-dim data?

**Comment by umar456** [comment]
We don't currently have plans to support >4 dimensional data. Additional dimensions tend to add complexity and overhead to the underlying algorithms which tends to affect performance. We chose 4D arrays as a good compromise between speed and functionality.

**Comment by pavanky** [comment]
To clarify what @umar456 is saying, this is the limit of the underlying C API. It might be possible to support this other languages (such as the rust wrapper) using a ton of hackery.

**Comment by MichaelHirn** [comment]
Thanks @umar456 and @pavanky for clarification. So if I understand it correctly, Arrayfire (the mother library) itself is restricted to 4D arrays, which is why you would rather solve it there than here in the rust wrapper.

And in Arrayfire there are currently no plans either for lifting the 4D restriction, as it would complicate things.
