### ISSUE TITLE
Better Arrayfire Expressions Syntax

### ISSUE THREAD

**Issue by adamcavendish** [arrayfire/arrayfire-rust#45]
I am thinking of a better way of expressing arrayfire expressions in rust, however still needs some work on the design.

We can create macros describing an arrayfire expressions, like this:
```rust
let dims = af::Dim4::new(&[10, 10, 1, 1]);
let a = af::randu(dims, Aftype::F32)
let result = af::expression!(
    |expr, err| println!("'{}' Calculation failure, error: {}", expr, err),
    af::sin(1) / a + a);

let result = af::retry!(
    3,
    |expr, err| println!("'{}' Calcuation failure, error: {}", expr, err),
    af::retry_expression!(af::sin(1) / a + a));
```

Most of the time I'm quite bored with a lot of `and_then` appearing in my arrayfire-rust code, and creating a lot of disambiguation in expresstions.

However, the with the error appearing, generally people will:
1. print the error, save the state and calculated results and let it panic. Then, let other daemon scripts restart the program.
2. retry the calculation

**Comment by adamcavendish** [comment]
Probably similar methods can help clean up expressions into syntax like arrayfire-c / arrayfire-c++

**Comment by jramapuram** [comment]
This does alleviate a lot of the unwrap() calls all over the place. I like the idea.
One question about the retry mechanism: any reason we need an `af:retry_expression!` internally? Can't it be handled in the top level macro?

**Comment by adamcavendish** [comment]
Yeah, I think it'd be possible.

And another idea: setting up arrayfire context (but this might require a lot of work for elegant implementation, if not using global variables)

```rust
af::set_error_handling(|expr, err| println!("'{}' Calcuation failure, error: {}", expr, err));
let result = af::sin(1) / a + a;
```

**Comment by 9prady9** [comment]
@adamcavendish & @jramapuram 

I believe the elegant way would be to use something like [Compiler syntax extension](https://doc.rust-lang.org/stable/book/compiler-plugins.html#syntax-extensions) to parse expressions and process the tokens. I don't think we can do what we want with regular macros in efficient way. If you were referring to compiler plugin earlier, then we are on same page.

You can check out the roman numerals example in the link i provided above and we would have to do something similar in our case except that we would be handling expressions with symbols of type Array's or scalars and ArrayFire functions.

**Comment by adamcavendish** [comment]
Yep, we might fight for any great impl to make the macro work as expected and most efficient, either ordinary macros or compiler syntax extension.

**Comment by jramapuram** [comment]
@9prady9 : Can you provide a little code widget for what you would like to use the compiler syntax extension for? I'm guessing it will look something like:

```rust
af::register_error_cb(|err| println!("My err was {}", err));
af_parse!(sin(1) / a + a);  //where this macro is implemented via a parse tree
```

Is that what you had in mind? Any benefit in the parse tree over the simple macro?

**Comment by 9prady9** [comment]
@adamcavendish @jramapuram Yes that is similar to what i have in mind. But what i don't understand is how are we going to handle compound expressions in regular macros - the example we have been using `sin(1)/a + a`? I don't know everything about Rust macros, but i don't think that is possible using regular macros. @jramapuram what do you mean by af(c lib) ? the ArrayFire C-API ?

**Comment by jramapuram** [comment]
@9prady9 : yes the C library. One easy solution would be if restructured the operator overloads to return a `Result<AfErr, Val>` type and then do a match internally in the macro. This is of course the naive solution. 

So something like this  [this probably doesn't compile]
```rust
macro_rules! af_parse {
    ($e: expr) => {{
        match expr {
           Err(e) => //callback,
           Ok(v) => v,
        }
    }} 
}
```

The key here is that the expression will be evaluated outside and just passed into the macro.
But yea, not quite elegant. 

One **serious** issue from the above is that if the first part does in fact return an `AfErr` we would be trying to pass that to another function, eg: sin(a) returned an `AfErr` which would be used in the `operator+` which would not allow this. Would modifying the function prototypes to accept a `Result<AfErr, Array>` instead of an `Array` resolve this? (as we can directly return the error)

**Comment by 9prady9** [comment]
Yes, they might resolve it but it is generally not a good idea to pass Result objects as input parameters to functions or operators - came to this conclusion after debating/reading a lot on rust user forums. Also, making the functions/operators accept result types will force the library to have two versions for each and every type of operator/function that takes regular `Array` and `Result<Array,..>` object, which is lot of redundant code and probably not a good design, especially if we have alternatives. These are the problems i see with using regular macros, hence my opinion of not using them for this situation. If we can't make it work with compiler plugin, we can resort to regular macros.

**Comment by jramapuram** [comment]
What about just returning an `Array` instead of the `Result<AfErr, Array>` but internally calling the callback when there is an error. This will create a natural breakpoint where the user can manage the error.

**Comment by 9prady9** [comment]
That should work, but we have to do this change for all the functions in the library to be consistent.

**Comment by pavanky** [comment]
@arrayfire/rust-devel 

I am bored and awake on a weekend, so I started reading a bunch of things (including the options mentioned here).

Here are my thoughts:

- The way arrayfire is implemented, there are very few errors you want to recover from at runtime (for example an out of memory error / backend not available etc). Most other errors should abort the program with the proper message.

- The API in its current form is not going to get a lot of people to scientific programming in rust using arrayfire.

- A few other numerical libraries written in rust are simply ignoring the error handling.

Based on this, I think we should just get rid of returning errors for every function and have the following:

- A function set an error handler for the rest of the program. The registry by default only function that panics when it sees an error.
- A function to get last error.
- A macro to handle the error within an expression. 

Code would be something like this:

```
let id = af::set_error_handler(my_default_error_handler)
let a = af::randu(dims, Aftype::f32)
let b = af::sin(a) + 0.01

af_try!(af::set_backend(CPU), af::set_backend(CUDA))
```

Let me know what you guys think.

**Comment by pavanky** [comment]
I know this is going to break the API, but better break it now than later.

**Comment by pavanky** [comment]
There is also [std::panic::catch_unwind](https://doc.rust-lang.org/beta/std/panic/fn.catch_unwind.html) coming up in rust 1.9 (scheduled for May 16) which sort of emulates try/catch.

It is called [std::panic::recover](http://doc.rust-lang.org/std/panic/fn.recover.html) in it's current unstable form.

I think this makes it easier to use panics in our code.

**Comment by jramapuram** [comment]
I like the `std::panic::catch_unwind` solution. I think it will probably parallel functionionality similar to arrayfire C++

**Comment by pavanky** [comment]
@jramapuram `catch_unwind` just replaces `af_try!` from my code. Everything else should still be consistent

**Comment by jramapuram** [comment]
@pavanky : Ah gotcha. Yea, I think the error handler function would be ideal (thus I suggested it ;p ). There are some errors that can happen for every different function though, just ran into one yesterday: i.e. double precision was not available and all the related functions threw errors.

**Comment by 9prady9** [comment]
@pavanky I have replied to what you have suggested below inline:

- The way arrayfire is implemented, there are very few errors you want to recover from at run time (for example an out of memory error / backend not available etc). Most other errors should abort the program with the proper message. 

`Do not agree on this, there might be applications where given a set of inputs for a function are invalid, you might still want to continue the program to process subsequent requests A typical example of such scenario is a service type application that is just processing requests on demand, but executing a specific standalone task.`

- The API in its current form is not going to get a lot of people to scientific programming in rust using arrayfire.

`Agree`

- A few other numerical libraries written in rust are simply ignoring the error handling.

`Not sure about this, they might be having some sort of error handling ?`

`std::panic::catch_unwind` might make the code look c++ish but this is not c++. Also, it would force us to panic for every error to use try/catch(unwind) style programming.

I am neither against nor for the idea of using error handler function, that is registered on the onset of the program as long as the code looks easy to read and understand which is what we are trying to address here. This idea is the only one that seems like one that fits our needs in least disruptive way. However, this would beget lot of change in the API as @pavanky and others have pointed out.

**Comment by pavanky** [comment]
> Do not agree on this, there might be applications where given a set of inputs for a function are invalid, you might still want to continue the program to process subsequent requests A typical example of such scenario is a service type application that is just processing requests on demand, but executing a specific standalone task.

Again, this kind of scenario is the exception, not the norm. Which means there should be a way to handle errors, but there is no reason we force users to handle errors at every step.

> std::panic::catch_unwind might make the code look c++ish but this is not c++. Also, it would force us to panic for every error to use try/catch(unwind) style programming.

That is not a good reason at all. That functionality is part of rust. We can't just ignore it because it will make it look like C++.  However this will only be used when user does not set an error handling function.

**Comment by 9prady9** [comment]
After much discussion (both internally and on github), we have decided on implementing the following changes to deal with error handling:

1.  A new function to register/set an function/closure as an application wide error handling mechanism shall be provided. The provided function/closure shall be executed when an error happens.
2. All functions/operations(overloading operators/traits) shall panic by default upon encountering unexpected inputs unless a function/closure is registered for error handling as explained in point (1)

The above changes will result in effectively two choices for error handling.

1. Don't do anything, the program will panic upon errors.
2. Register an error handler (implemented by the user) that will handle errors.

**Comment by jramapuram** [comment]
Nice! An example error handler would be appreciated :)
