### ISSUE TITLE
How to config the rust wrapper using CUDA and how to modify the build.conf file to build arrayfire submodule available in the rust wrapper

### ISSUE THREAD

**Issue by fuyingfuying** [arrayfire/arrayfire-rust#65]
Hi, firstly, thanks for your great project. I love rust and arrayfire. I'm a newer to arrayfire. I've installed the latest official cuda 7.5 installer and the latest official  arrayfire installers( linux v3.3.1 64-bit) under my ubuntu 15.10. And I use the default configuration follow the official doc. But When I successfully build the arrayfire-rust lib and try to run the "unified" example in the ./examples folder. It shows me i only have cpu and opencl backends. CUDA backend can not be found. 
![fuying fuying-kylin -rustprojs-arrayfire-rust_010](https://cloud.githubusercontent.com/assets/12774287/14231012/ad161a10-f9a4-11e5-9cf0-7170408f6e15.png)

So my question is : 
**# how to config to let this wrapper to support cuda in my computer. **
By the way, the official cpp examples can be built successfully using Cuda.
![benchmarks_011](https://cloud.githubusercontent.com/assets/12774287/14231010/9dde41e4-f9a4-11e5-89b7-26d3ab1888b5.png)

Another question is how to modify the build.conf file to build arrayfire submodule available in the rust wrapper. When I git clone the source from github. The build.conf file looks like:
![build conf -home-fuying-rustprojs-arrayfire-rust atom_012](https://cloud.githubusercontent.com/assets/12774287/14231024/1f160738-f9a5-11e5-831c-dd614ab88252.png)
How can I config these options:
    "glew_static": "OFF",
    "freeimage_type": "DYNAMIC",
    "cpu_fft_type": "FFTW",
    "cpu_blas_type": "LAPACKE",
    "cpu_lapack_type": "LAPACKE",

    "freeimage_dir": "E:\\Libraries\\FreeImage\\Dist",
    "fftw_dir": "E:\\Libraries\\fftw-3.3.4",
    "acml_dir": "",
    "mkl_dir": "",
    "lapacke_dir": "E:\\Libraries\\lapack",
    "glew_dir": "E:\\Libraries\\GLEW",
    "glfw_dir": "E:\\Libraries\\glfw3",
    "boost_dir": "E:\\Libraries\\boost_1_56_0",

    "cuda_sdk": "/usr/local/cuda",
    "opencl_sdk": "/usr"
By the way, I check the path of cuda libs, "cuda_sdk" option seems correct. So, what's the problem with my config.
![cuda_013](https://cloud.githubusercontent.com/assets/12774287/14231035/f093c3d6-f9a5-11e5-8802-f12d7d717caa.png)

**Comment by 9prady9** [comment]
@fuyingfuying I believe @shehzan10 has already this question on forums. Just in case you haven't seen that yet.

- Your LD_LIBRARY_PATH needs to include /usr/local/cuda/lib64 and /usr/local/cuda/nvvm/lib64. You also need to add the path to the ArrayFire libraries AF_PATH/lib.
- The config variable `use_lib` in the `build.conf` file informs the rust build script to use already built binaries while compiling the ArrayFire rust wrapper. When this option is being used, you wouldn't need to set any of the other options as the script will try to find required dependencies from standard installation paths. This standard path for ArrayFire binaries is `$AF_PATH/lib` where `AF_PATH` is where you have installed ArrayFire.

**Comment by fuyingfuying** [comment]
@9prady9 @shehzan10 thanks for your help, i try it and reply you later

**Comment by fuyingfuying** [comment]
@9prady9 @shehzan10 thank you, I just don't add  /usr/local/cuda/lib64 to the LD_LIBRARY_PATH, now it works
![fuying fuying-kylin -rustprojs-arrayfire-rust_015](https://cloud.githubusercontent.com/assets/12774287/14282718/433ca58a-fb72-11e5-9482-b7e0007f1a69.png)
![fuying fuying-kylin -rustprojs-arrayfire-rust_016](https://cloud.githubusercontent.com/assets/12774287/14282719/433e4bec-fb72-11e5-9b55-fe85f947b6a8.png)
![fuying fuying-kylin -rustprojs-arrayfire-rust_017](https://cloud.githubusercontent.com/assets/12774287/14282720/43407e12-fb72-11e5-8f0a-18fd61eed51d.png)
