### ISSUE TITLE
Examples are not compiling

### ISSUE THREAD

**Issue by DerGroncki** [arrayfire/arrayfire-rust#67]
I just installed arrayfire on windows 10 pro.

I am not able to compile any example e.g. if I compile the snow.rs example I get
main.rs:20:17: 20:20 error: too many type parameters provided: expected at most 0 parameters, found 1 parameter [E0087]
main.rs:20         randu::<f32>(dims).as_ref()

Ok I am able to fix this but when I run the example I get error: Process didn't exit successfully: (...) (exit code: 3221225477)

Any hints to fix this would be great.

Thanks.

Michael

Edit:
BTW: The arrayfire-dotnet (c#) is running wihout any problems e.g. if I run the example HelloWorld I get

ArrayFire v3.3.1 (OpenCL, 64-bit Windows, build f53efc3)
[0] NVIDIA  : GeForce GTX 960M, 2048 MB
-1- INTEL   : Intel(R) HD Graphics 530, 6483 MB
-2- INTEL   : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 16227 MB
arr1
[3 3 1 1]
   -0.8708    -1.3035     1.1526
    0.4579    -1.0310     1.1717
    0.2983     0.5926     0.3209

and so on....

**Comment by 9prady9** [comment]
@DerGroncki Does this problem happen in the same environment as #66 ?

**Comment by DerGroncki** [comment]
Yes
