### ISSUE TITLE
Require Rust 1.8

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-rust#71]
With the error handling push I started seeing errors like this:

```bash
src/arith/mod.rs:387:1: 387:55 note: in this expansion of bit_assign_func! (defined in src/arith/mod.rs)
src/arith/mod.rs:376:13: 382:14 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
src/arith/mod.rs:376             fn $fn_name(&mut self, rhs: Array) {
src/arith/mod.rs:377                 let mut idxrs = Indexer::new();
src/arith/mod.rs:378                 idxrs.set_index(&Seq::<f32>::default(), 0, Some(false));
src/arith/mod.rs:379                 idxrs.set_index(&Seq::<f32>::default(), 1, Some(false));
src/arith/mod.rs:380                 let tmp = assign_gen(self as &Array, &idxrs, & $func(self as &Array, &rhs));
src/arith/mod.rs:381                 mem::replace(self, tmp);
```

Bumping my rust install to `1.8` solved this.

**Comment by 9prady9** [comment]
Yes i saw similar errors on build servers too. But it is just related to rust version like you found out. I have implemented new traits that were release in 1.8 Rust. Hence the problem you saw. I am checking if we can selectively enable these traits based on Rust version, do you have any idea about that ?

**Comment by 9prady9** [comment]
Looks like we can use something like this crate
https://github.com/Kimundi/rustc-version-rs

**Comment by jramapuram** [comment]
This works! We can incorporate it into `build.rs`
