### ISSUE TITLE
Plans to integrate rust-ndarray?

### ISSUE THREAD

**Issue by SuperFluffy** [arrayfire/arrayfire-rust#77]
Do you have plans to integrate `arrayfire-rust` with [`rust-ndarray`](https://github.com/bluss/rust-ndarray)? I understand that `arrayfire` supports up to 4 dimensions, so I am not calliing for actually implementing n-dimensional arrays as requested [here](https://github.com/arrayfire/arrayfire-rust/issues/44).

I believe `ndarray` is currently the most mature library for handling arrays in Rust, and I am actively using it in my projects (integration of high-dimensional ODEs). It would be great if there was a straight-forward way of combining this with `arrayfire`.

**Comment by pavanky** [comment]
@SuperFluffy We welcome any contributions :) Btw I think it is simplest to have bridge functions between the two libraries rather than integrating it whole.

**Comment by jramapuram** [comment]
No sure I would say ndarray is the leader. Looks like nalgebra is it: https://crates.io/keywords/matrix?sort=downloads

In either case I think a better solution would be to be able to use arrayfire for both CPU & GPU.

**Comment by bluss** [comment]
ndarray and nalgebra are only slightly overlapping. nalgebra is good for 2d matrices and linear algebra with focus on small matrices. ndarray handles n-dimensional arrays but almost no linear algebra.

ndarray being built mainly for in-memory usage might be hard to integrate seamlessly with arrayfire?

**Comment by 9prady9** [comment]
@SuperFluffy  @bluss 

Easiest and simple way would be to write bridge functions between arrayfire-rust and ndarray as @pavanky mentioned. Also, ArrayFire has many linear algebra routines which may be a `superset` of the routines provided in `ndarray`. So, as of now we don't have any plans to integrate ndarray into this project.
