### ISSUE TITLE
Array Indexing

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-rust#79]
Is it possible at this point to indexing arrays by implementing `IndexMut`, etc? It would be nice to do be able to do the following `a[x_index][y_index][z_index][d_index]`

Ideally it would be great to be able to have ranges inside as well [numpy style], eg:
`a[0..x_index][y_index][z_index][d_index]`

and even negative indexing to pick elements from the end:
`a[-1][y_index][z_index][d_index]`

[Relevant SO post](http://stackoverflow.com/questions/25106355/index-and-indexmut-implementations-to-return-borrowed-vectors). I believe dynamic types are already in now?

**Comment by 9prady9** [comment]
Being able to do such terse indexing would be a good addition. Yes, i have heard that dynamic types are in, but i am not aware of all of the details. Will have to look into them.

**Comment by 9prady9** [comment]
@jramapuram I was thinking about how to implement this using the c++ version of ArrayFire as baseline. What i have noticed is that c++ API in ArrayFire heavily uses assignment operator overload and we have no control of assignment operator in Rust, please correct me if i am wrong in this observation. So, i am wondering how crucial is this for implementing indexing in above fashion.

**Comment by jramapuram** [comment]
@9prady9 : Isn't assignment simply `Copy` or `Clone` in rust? We have an impl of `Clone`. However, not sure if I understand how this is related. Wouldn't it just be implementing the `IndexMut` operations? Inside that it would be calls to `af::index` or one of the other indexing functions in `index.rs`

**Comment by 9prady9** [comment]
True, i forgot about `clone` trait (`copy` is not available if `drop` is implemented - unless this changed recently).

ArrayFire's C++ wrapper uses proxy pattern for indexing efficiently. You can have a peek at the following sections of code to understand how it is being done in that wrapper.

* [proxy class declaration](https://github.com/arrayfire/arrayfire/blob/devel/include/af/array.h#L47)
* [proxy class implementation](https://github.com/arrayfire/arrayfire/blob/80f2e64f4fb06844d8a6cf6d908496d05a87b716/src/api/cpp/array.cpp#L88)
* [proxy class assignment operator overload](https://github.com/arrayfire/arrayfire/blob/devel/src/api/cpp/array.cpp#L450)

I believe we might have to do something similar in Rust too after we get the index ranges from `Index` and `IndexMut` traits. Hence, i was thinking about the assignment operation, `clone` trait didn't cross my mind at that point.

**Comment by jramapuram** [comment]
How about a slicing macro like this? http://bluss.github.io/rust-ndarray/master/ndarray/macro.s.html

**Comment by Timmmm** [comment]
Maybe I'm missing something, but is there *any* way to set a single element at the moment? I couldn't find a `set_element()` function or anything like that...

**Comment by 9prady9** [comment]
@Timmmm You should be using either [assign_gen](http://arrayfire.org/arrayfire-rust/arrayfire/fn.assign_gen.html) or [assign_seq](http://arrayfire.org/arrayfire-rust/arrayfire/fn.assign_seq.html) depending on your use case.

But ideally, such writes are only good in performance if you are writing considerable number of elements. Writing single elements is very inefficient in terms of data transfers done from host to GPU/accelerator device.

**Comment by 9prady9** [comment]
@jramapuram Are macros allowed on left hand side of equal operator in rust ?

**Comment by 9prady9** [comment]
@jramapuram I have looked into the possible ways of doing this. I don't think we can implement traits `Index` and `IndexMut` the way we want because the `Clone` is an explicit operation and the code would like below

```rs
let b = (a[Seq::default()][Seq::new(0.0, 1.0, 0.1)]).clone(); // assignment
```
We are limited by the fact that Copy can't be implemented for a struct has Drop, because it is a wrapper object managing backend resource.

If you can think of any other alternatives, please suggest.

**Comment by 9prady9** [comment]
Closing the issue for now, please reopen if there is a work around to above mentioned restrictions.
